In [1]:
import sys
import os

# 현재 test.ipynb는 miraeasset2025/TEST 안에 있으므로
# 한 단계 위로 가서 sys.path에 'MiraeAsset' 경로를 추가해야 패키지 인식 가능
sys.path.append(os.path.abspath("../.."))

from miraeasset2025.analyst_report.llama_parser import LlamaParser

/home/user/exercise_j/MiraeAsset/virtual/mirae/lib/python3.12/site-packages/pykrx/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [2]:
parser = LlamaParser(pdf_path='/home/user/exercise_j/MiraeAsset/miraeasset2025/analyst_report/data/미래에셋증권_종목보고서_출처_한경컨센서스_(SK증권).pdf')

2025-07-26 15:14:38 - [INFO] [Step 1] 초기화 시작
2025-07-26 15:14:38 - [INFO] KOSPI 종목 데이터 호출 시작
2025-07-26 15:14:38 - [INFO] KOSPI 종목 데이터 호출 완료


In [3]:
parser.analyze()

2025-07-26 15:14:41 - [INFO] [Step 2] PDF 전체 분석 시작
2025-07-26 15:14:41 - [INFO] [Step 3] 본문 데이터 파싱 시작
2025-07-26 15:14:45 - [INFO] [Step 4] 본문 파싱 완료
2025-07-26 15:14:45 - [INFO] [Step 5] 텍스트 유효성 검증 시작
2025-07-26 15:14:45 - [INFO] [Step 6] 텍스트 유효성 검증 완료
2025-07-26 15:14:45 - [INFO] [Step 7] 파싱 데이터 매핑 시작
2025-07-26 15:14:45 - [INFO] 원문에서 메타데이터를 추출합니다.
2025-07-26 15:14:45 - [INFO] [Step 8] 원문데이터에서 메타데이터 파싱 시작
2025-07-26 15:14:45 - [INFO] Initialized with 4 API keys, starting from index 0
2025-07-26 15:14:47 - [INFO] 티커 검증 시작 - 현재 상태: name=미래에셋증권, ticker=006800
2025-07-26 15:14:47 - [INFO] [Step 9] 본문 줄글 데이터 파싱 시작
2025-07-26 15:14:47 - [INFO] Initialized with 4 API keys, starting from index 0
2025-07-26 15:14:50 - [INFO] [Step 10] 분석 결과 요약
2025-07-26 15:14:50 - [INFO] [Step 11] 전체 분석 완료



PDF 분석 완료:
- 파일명: 미래에셋증권_종목보고서_출처_한경컨센서스_(SK증권).pdf
- 추출된 텍스트 길이: 10,949자

분석된 내용:
- 종목명: 미래에셋증권
- 종목코드: 006800
- 작성날짜: 2025-07-04
- 증권사: SK증권


In [6]:
parser.raw_paragraph

'ㅛㄴ \n \n \n미래에셋증권 (006800/KS) \n정상화된 이익 예상되나 다소 과도한 기대감 \nCompany Data \n발행주식수 \n57,032 만주 \n시가총액 \n11,053 십억원 \n주요주주 \n \n미래에셋캐피탈(외17) \n32.37% \n자사주 \n22.98% \n \n \nStock Data \n주가(25/07/04) \n19,380 원 \nKOSPI \n3,054.28 pt \n52주 최고가 \n23,450 원 \n52주 최저가 \n6,660 원 \n60일 평균 거래대금 \n56 십억원 \n목표주가 18,000 원으로 상향, 투자의견 중립으로 조정 \n미래에셋증권의 목표주가를 1) 무위험수익률, 2) 실적 추정치 조정 및 3) 할인율 조정\n등을 반영하여 18,000 원으로 상향한다. 목표주가는 25E BVPS 17,788 원에 Target \nPBR 0.99 배를 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 \n상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 \n등 영향으로 투자의견 중립을 제시한다. \n \n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려 \n지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 \n완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손\n실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부\n동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최\n근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영\n향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이\n익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 \n정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등\n에 대한 기대감

'ㅛㄴ \n \n \n미래에셋증권 (006800/KS) \n정상화된 이익 예상되나 다소 과도한 기대감 \nCompany Data \n발행주식수 \n57,032 만주 \n시가총액 \n11,053 십억원 \n주요주주 \n \n미래에셋캐피탈(외17) \n32.37% \n자사주 \n22.98% \n \n \nStock Data \n주가(25/07/04) \n19,380 원 \nKOSPI \n3,054.28 pt \n52주 최고가 \n23,450 원 \n52주 최저가 \n6,660 원 \n60일 평균 거래대금 \n56 십억원 \n목표주가 18,000 원으로 상향, 투자의견 중립으로 조정 \n미래에셋증권의 목표주가를 1) 무위험수익률, 2) 실적 추정치 조정 및 3) 할인율 조정\n등을 반영하여 18,000 원으로 상향한다. 목표주가는 25E BVPS 17,788 원에 Target \nPBR 0.99 배를 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 \n상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 \n등 영향으로 투자의견 중립을 제시한다. \n \n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려 \n지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 \n완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손\n실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부\n동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최\n근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영\n향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이\n익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 \n정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등\n에 대한 기대감은 제한적이라고 판단한다. 미래에셋증권의 25E PER 은 연간 약 1 조원\n내외의 이익 기준 약 11.4 배 수준으로 다른 대형 증권사 5.4~8.3 배 수준 대비 높은 \n프리미엄이 적용된 가격으로 거래되고 있으나 현재 밸류에이션이 정당화되기 위해서는 \n상대적으로 낮은 ROE 등 자본 활용의 효율성 측면의 제고가 필요하다고 판단한다. \n \n2Q25 지배순이익 2,789 억원(+40.3% YoY) 예상 \n미래에셋증권의 2Q25 지배순이익은 2,789 억원(+40.3% YoY)로 컨센서스를 상회\n할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM \n수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도PF 수익 회\n복 등 영향으로 전분기 대비 개선되는 모습을 기대한다. 2Q25 기준 ROE 는 연율화 \n기준 약 9.1%를 전망한다. \n2025-07-07 \n주가 및 상대수익률 \n \n-9\n11\n31\n51\n71\n91\n111\n131\n151\n171\n191\n5,000\n7,000\n9,000\n11,000\n13,000\n15,000\n17,000\n19,000\n21,000\n23,000\n25,000\n24.6\n24.9\n24.12\n25.3\n25.6\n미래에셋증권\nKOSPI대비상대수익률\n(원)\n(%)\nAnalyst \n설용진 \n \ns.dragon@sks.co.kr \n3773-8610 \n중립(하향) \n목표주가: 18,000 원(상향) \n현재주가: 19,380 원 \n상승여력: -7.1% \n영업실적 및 투자지표 \n구분 \n단위 \n2022A \n2023A \n2024A \n2025E \n2026E \n2027E \n순영업수익 \n십억원 \n2,176 \n1,887 \n2,832 \n3,131 \n3,370 \n3,515 \n영업이익 \n십억원 \n836 \n521 \n1,188 \n1,325 \n1,500 \n1,574 \n순이익(지배주주) \n십억원 \n639 \n327 \n922 \n1,013 \n1,143 \n1,198 \nEPS(계속사업) \n원 \n991 \n504 \n1,512 \n1,699 \n1,914 \n2,023 \nPER \n배 \n6.1 \n15.1 \n5.3 \n11.4 \n10.1 \n9.6 \nPBR \n배 \n0.46 \n0.52 \n0.49 \n1.09 \n1.02 \n0.96 \n배당성향 \n% \n19.3 \n27.4 \n15.9 \n17.4 \n18.0 \n14.7 \nROE \n% \n6.4 \n3.2 \n8.0 \n8.1 \n8.6 \n8.52 \n목표주가 산정 Table \n \n항목 \n비고 \n내용 \nSustainable ROE (a) \n2025E ~2027F ROE 평균 \n8.4% \nCost of Equity (b) \n무위험수익률 2.75%, 리스크 프리미엄 4.9%, 베타 1 기준 \n7.7% \nGrowth (c)  \n보수적으로 0% 가정 \n0.0% \nDiscount (d) \n초대형 IB 라이선스 및 밸류업 공시 등 바탕으로 디스카운트 부여. 낮아진 CoE 감안하여 추가 하향 조정 \n10% \nTarget PBR \n(a-c)/(b-c)x(1-d) \n        0.99  \n목표주가 \n2025F BPS 17,797원에 Target PBR 적용 \n    18,000  \n현재가 \n  \n    19,380  \nUpside / Downside \n \n-7.1% \n투자의견 \n  \nHold \n자료: SK증권 추정 \n  \n시나리오별 목표주가 상승/하락 여력 \n \n항목 \n비고 \n내용 \nUpside case \n  \n19% \n   Sustainable ROE \n해외 투자자산 관련 평가처분손익 개선, 트레이딩 등 호조 \n9.9% \n   COE \n무위험수익률 2.75%, 리스크 프리미엄 4.9%, 베타 1 기준 \n7.7% \n   Growth \n보수적으로 0% 가정 \n0.0% \n   Premium/Discount \n예상 대비 가파른 실적 회복 및 주주환원 확대 \n0.0% \n   Fair P/B \n(a-c)/(b-c)x(1-d) \n        1.30  \n목표주가(Bull case) \n2025F BPS 17,797원에 Target PBR 적용 \n    23,100  \nDownside case \n  \n-33% \n   Sustainable ROE \n해외 부동산 손실 가중, 트레이딩 등 부진 \n6.9% \n   COE \n무위험수익률 2.75%, 리스크 프리미엄 4.9%, 베타 1 기준 \n7.7% \n   Growth \n보수적으로 0% 가정 \n0.0% \n   Premium/Discount \n부동산 PF/해외 부동산 관련 손실 악화 \n-20.0% \n   Fair P/B \n(a-c)/(b-c)x(1-d) \n        0.72  \n목표주가(Bear case) \n2025F BPS 17,797원에 Target PBR 적용 \n    12,900  \n자료: SK증권 추정 \n \n실적 추정치 조정 \n \n \n \n2024 \n2025E \n2026E \n2027E \n순영업수익 \n수정 후 \n2,832  \n3,131  \n3,370  \n3,515  \n \n수정 전 \n \n3,023  \n3,210  \n3,334  \n  \n증감률(%) \n  \n3.6  \n5.0  \n5.4  \n영업이익 \n수정 후 \n1,188  \n1,325  \n1,500  \n1,574  \n \n수정 전 \n \n1,226  \n1,354  \n1,409  \n  \n증감률(%) \n  \n8.0  \n10.8  \n11.7  \n세전이익 \n수정 후 \n1,224  \n1,369  \n1,550  \n1,625  \n \n수정 전 \n \n1,224  \n1,349  \n1,405  \n  \n증감률(%) \n  \n11.8  \n14.9  \n15.6  \n지배지분 순이익 \n수정 후 \n922  \n1,013  \n1,143  \n1,198  \n \n수정 전 \n \n906  \n994  \n1,035  \n  \n증감률(%) \n  \n11.8  \n15.0  \n15.8  \n자료: SK증권 추정설용진 \n3 \n미래에셋증권 – 연결 기준 분기별 실적 추이 및 전망 \n \n(십억원) \n2Q24 \n3Q24 \n4Q24 \n1Q25 \n2Q25E \n3Q25E \n% QoQ \n% YoY \n순영업수익 \n699.3  \n764.4  \n690.3  \n812.9  \n803.6  \n776.6  \n-1.1  \n14.9  \n수수료손익 \n247.9  \n271.9  \n265.4  \n240.4  \n365.0  \n362.2  \n51.8  \n47.2  \nBrokerage \n175.2  \n182.9  \n178.2  \n239.6  \n258.9  \n263.0  \n8.0  \n47.7  \nWM \n61.6  \n60.2  \n59.2  \n71.7  \n73.1  \n73.8  \n2.0  \n18.7  \nIB \n19.2  \n29.9  \n20.3  \n19.4  \n28.0  \n20.6  \n44.5  \n46.2  \n기타 \n-8.0  \n-1.1  \n7.6  \n-90.3  \n5.0  \n4.9  \n흑전 \n흑전 \n이자손익 \n113.6  \n78.5  \n90.7  \n102.4  \n76.8  \n107.5  \n-25.0  \n-32.4  \n트레이딩 및 기타 \n337.8  \n414.0  \n334.2  \n470.1  \n361.8  \n306.8  \n-23.0  \n7.1  \n판매관리비 \n426.0  \n393.6  \n416.7  \n466.8  \n446.6  \n422.8  \n-4.3  \n4.8  \n영업이익 \n273.3  \n370.8  \n273.6  \n346.2  \n357.0  \n353.8  \n3.1  \n30.6  \n세전이익 \n276.7  \n356.8  \n358.7  \n346.1  \n378.1  \n362.3  \n9.3  \n36.7  \n당기순이익 \n201.2  \n290.1  \n263.7  \n258.2  \n279.8  \n268.1  \n8.4  \n39.1  \n지배지분순이익 \n198.7  \n291.2  \n267.0  \n258.7  \n278.9  \n267.2  \n7.8  \n40.3  \n자산 \n139,859  \n135,390  \n137,192  \n132,775  \n137,628  \n138,273  \n3.7  \n-1.6  \n부채 \n128,333  \n123,932  \n124,961  \n120,441  \n125,015  \n125,473  \n3.8  \n-2.6  \n자본 \n11,526  \n11,458  \n12,231  \n12,334  \n12,613  \n12,800  \n2.3  \n9.4  \nROE(%) \n7.2  \n10.2  \n9.0  \n8.5  \n9.1  \n8.5  \n0.6  \n1.9  \n자료: 미래에셋증권, SK증권 추정 \n \n미래에셋증권 – 연금자산 적립금 지속적으로 증가 추세 \n미래에셋증권 – 해외주식 잔고 양호한 흐름 지속 \n \n \n자료: 미래에셋증권, SK증권 \n자료: 미래에셋증권, SK증권 \n \n \n \n0 \n10 \n20 \n30 \n40 \n50 \n25/04 25/05\n2Q24\n3Q24\n4Q24\n1Q25\n2Q25\n퇴직연금\n개인연금\n(조원)\n0 \n10 \n20 \n30 \n40 \n50 \n25/04 25/05\n2Q24\n3Q24\n4Q24\n1Q25\n2Q25\n해외주식잔고\n(조원)4 \n미래에셋증권 – 별도 기준 분기별 실적 추이 및 전망 \n \n(십억원) \n2Q24 \n3Q24 \n4Q24 \n1Q25 \n2Q25E \n3Q25E \n% QoQ \n% YoY \n순영업수익 \n555.3  \n572.8  \n393.9  \n539.3  \n599.3  \n567.9  \n11.1  \n7.9  \n수수료손익 \n240.6  \n248.7  \n239.0  \n253.0  \n296.4  \n291.9  \n17.2  \n23.2  \nBrokerage \n153.0  \n155.6  \n164.1  \n180.8  \n195.3  \n198.4  \n8.0  \n27.7  \nWM \n67.8  \n67.1  \n66.2  \n73.7  \n75.1  \n75.9  \n2.0  \n10.8  \nIB \n19.9  \n31.1  \n22.4  \n21.4  \n30.9  \n22.7  \n44.5  \n55.3  \n기타 \n0.0  \n-5.1  \n-13.7  \n-22.9  \n-5.0  \n-5.1  \n적지 \n적전 \n이자손익 \n68.1  \n49.0  \n55.6  \n70.2  \n72.8  \n82.9  \n3.7  \n6.8  \n트레이딩 및 기타 \n246.5  \n275.1  \n99.3  \n216.2  \n230.2  \n193.1  \n6.5  \n-6.6  \n판매관리비 \n290.1  \n283.2  \n273.5  \n311.4  \n309.6  \n308.1  \n-0.6  \n6.7  \n영업이익 \n265.2  \n289.6  \n120.4  \n227.9  \n289.7  \n259.8  \n27.1  \n9.2  \n세전이익 \n245.0  \n332.6  \n130.0  \n123.6  \n292.4  \n259.0  \n136.5  \n19.3  \n당기순이익 \n179.9  \n265.1  \n89.7  \n90.6  \n216.4  \n191.6  \n138.8  \n20.3  \n \n \n \n \n \n \n  \n \n \n자산 \n88,866  \n92,131  \n95,177  \n91,232  \n93,839  \n94,253  \n2.9  \n5.6  \n부채 \n79,335  \n82,340  \n85,287  \n81,374  \n83,765  \n84,067  \n2.9  \n5.6  \n자본 \n9,530  \n9,791  \n9,890  \n9,858  \n10,074  \n10,186  \n2.2  \n5.7  \nROE(%) \n7.6  \n11.0  \n3.6  \n3.7  \n8.7  \n7.6  \n5.0  \n1.1  \n자료: 미래에셋증권, SK증권 추정 \n \n미래에셋증권 – PER 밴드 차트 \n미래에셋증권 – PBR 밴드 차트 \n \n \n자료: 미래에셋증권, SK증권 추정 \n자료: 미래에셋증권, SK증권 추정 \n \n \n0 \n5,000 \n10,000 \n15,000 \n20,000 \n25,000 \n30,000 \n19/01\n20/07\n22/01\n23/07\n25/01\n주가\n3.0x\n5.5x\n8.0x\n10.5x\n13.0x\n(원)\n0 \n5,000 \n10,000 \n15,000 \n20,000 \n25,000 \n30,000 \n19/01\n20/07\n22/01\n23/07\n25/01\n주가\n0.30x\n0.50x\n0.70x\n0.90x\n1.10x\n(원)설용진 \n5 \n \n재무상태표 \n포괄손익계산서 \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n현금 및 현금성자산 \n8,194\n10,518\n16,669\n15,611\n14,483 \n순영업수익 \n1,887 \n2,832\n3,131\n3,370\n3,515 \nFVPL금융자산 \n44,783\n55,246\n56,980\n58,942\n60,972 \n수수료손익 \n900 \n1,042\n1,332\n1,521\n1,606 \nFVOCI금융자산 \n16,088\n17,578\n16,020\n16,378\n16,744 \nBrokerage \n557 \n721\n1,025\n1,112\n1,179 \nAC금융자산 \n51,175\n46,077\n45,251\n46,824\n48,457 \nWM \n211 \n236\n293\n306\n318 \n종속/관계기업투자지분 \n2,022\n1,614\n1,845\n1,845\n1,845 \nIB \n108 \n92\n89\n85\n89 \n기타자산 \n5,916\n6,158\n6,214\n6,214\n6,214 \n기타 \n24 \n-7\n-76\n19\n19 \n자산총계 \n128,177\n137,192\n142,979\n145,813\n148,715 \n이자손익 \n365 \n385\n352\n387\n417 \n투자자예탁금 \n10,926\n12,222\n12,482\n12,532\n12,582 \n트레이딩 및 기타 \n623 \n1,405\n1,448\n1,462\n1,493 \n발행어음 \n6,449\n7,473\n7,818\n7,976\n8,137 \n판매관리비 \n1,366 \n1,643\n1,807\n1,871\n1,941 \n매도파생결합증권 \n9,424\n6,559\n6,924\n7,063\n7,206 \n판관비율(%) \n72.4 \n58.0\n57.7\n55.5\n55.2 \n차입금/사채 \n68,422\n77,390\n81,931\n83,615\n85,333 \n영업이익 \n521 \n1,188\n1,325\n1,500\n1,574 \n기타부채 \n21,717\n21,317\n20,816\n20,732\n20,650 \n영업외손익 \n-142 \n36\n44\n50\n51 \n부채총계 \n116,938\n124,961 129,970\n131,918 133,907 \n세전이익 \n379 \n1,224\n1,369\n1,550\n1,625 \n지배주주지분 \n11,081\n12,067\n12,847\n13,735\n14,647 \n법인세 \n41 \n299\n354\n403\n422 \n자본금 \n4,102\n4,102\n4,102\n4,102\n4,102 \n법인세율(%) \n10.9 \n24.4\n25.8\n26.0\n26.0 \n자본잉여금 \n2,158\n2,157\n2,157\n2,157\n2,157 \n당기순이익 \n338 \n925\n1,015\n1,147\n1,202 \n이익잉여금 \n2,250\n2,250\n2,250\n2,250\n2,250 \n지배주주순이익 \n327 \n922\n1,013\n1,143\n1,198 \n기타자본 \n2,571\n3,558\n4,338\n5,225\n6,138 \n비지배지분순이익 \n11 \n4\n2\n4\n4 \n비지배주주지분 \n158\n164\n161\n161\n161 \n \n \n \n \n \n자본총계 \n11,239\n12,231\n13,008\n13,895\n14,808 \n \n \n \n \n \n증권 별도 재무제표 \n주요투자지표 \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n순영업수익 \n1,478\n2,068\n2,274 \n2,417 \n2,487 \n성장성(%) \n \n \n수수료손익 \n845\n971\n1,135\n1,195\n1,233 \n자산 \n20.7 \n7.0\n4.2\n2.0\n2.0 \nBrokerage \n482\n634\n773\n808 \n828 \n자본(지배주주지분) \n8.2 \n8.9\n6.5\n6.9\n6.6 \nWM \n227\n262\n301 \n314 \n327 \n순영업수익 \n-13.3 \n50.0\n10.6\n7.6\n4.3 \nIB \n110\n97\n98\n93\n98 \n지배순이익 \n-48.9 \n181.8\n9.9\n12.8\n4.8 \n기타 \n25\n-22\n-38\n-21 \n-21 \nEPS \n-49.2 \n200.1\n12.4\n12.7\n5.7 \n이자손익 \n212\n233\n305 \n359\n372 \nBPS \n9.7 \n11.8\n9.0\n6.9\n6.6 \n트레이딩 및 기타 \n421\n864\n834 \n863\n882 \nDPS \n-25.0 \n66.7\n20.0\n16.7\n-14.3 \n판매관리비 \n971\n1,143\n1,270\n1,319\n1,367 \n수익성(%) \n \n \n판관비율(%) \n65.7\n55.3\n55.9\n54.6 \n55.0 \nROE \n3.2 \n8.0\n8.1\n8.6\n8.5 \n영업이익 \n507\n924\n1,004 \n1,098 \n1,120 \nROA \n0.3 \n0.7\n0.7\n0.8\n0.8 \n영업외손익 \n-274\n4\n-101 \n1 \n1 \n밸류에이션(배) \n \n \n세전이익 \n233\n928\n902 \n1,100\n1,122 \nPER \n15.1 \n5.3\n11.4\n10.1\n9.6 \n법인세 \n-5\n229\n235 \n286 \n292 \nPBR \n0.5 \n0.5\n1.1\n1.0\n1.0 \n법인세율(%) \n-2.2\n24.7\n26.1 \n26.0 \n26.0 \n주당지표(원) \n \n \n당기순이익 \n238\n699\n667\n814 \n830 \nEPS \n504 \n1,512\n1,699\n1,914\n2,023 \n연결당기순이익 대비 비중(%) \n70.4\n75.5\n65.7 \n70.9\n69.0 \nBPS \n14,592 \n16,321\n17,797\n19,026\n20,290 \n자산총계 \n85,965\n95,177\n96,725\n98,557 100,40\n보통주 DPS \n150 \n250\n300\n350\n300 \n연결 자산총계 대비 비중(%) \n67.1\n69.4\n67.6\n67.6\n67.5 \n주주환원(%) \n \n \n부채총계 \n76,496\n85,287\n86,371 \n87,645 \n88,948 \n전체 배당성향 \n27.4 \n15.9\n17.4\n18.0\n14.7 \n연결 부채총계 대비 비중(%) \n65.4\n68.3\n66.5\n66.4 \n66.4 \n총주주환원율 \n52.6 \n39.8\n56.8\n52.9\n48.0 \n자본총계 \n9,468\n9,890\n10,354 \n10,912 \n11,456 \n보통주 배당수익률 \n2.0 \n3.1\n1.5\n1.8\n1.5 \n연결 자본총계 대비 비중(%) \n84.2\n80.9\n79.6\n78.5\n77.4 \n자본적정성(%) \n \n \n별도 ROE(%) \n2.6\n7.2\n6.6\n7.7\n7.4 \n구 NCR \n151.1 \n165.6\n162.6\n158.9\n154.9 \n별도 ROA(%) \n0.3\n0.8\n0.7\n0.8 \n0.8 \n신 NCR \n2,142.4 \n2,857.8\n2,918.8\n3,001.7\n3,059.3 \n자료: 미래에셋증권, SK증권 추정6 \n \n \n일시 \n투자의견 \n목표주가 \n목표가격 \n대상시점 \n괴리율 \n \n평균주가대비 \n최고(최저) \n주가대비 \n \n2025.07.07 \n중립 \n18,000원 \n6개월 \n \n \n \n \n \n2025.05.09 \n매수 \n14,200원 \n6개월 \n23.00% \n65.14% \n \n2025.02.10 \n매수 \n11,000원 \n6개월 \n-13.87% \n10.64% \n \n2024.09.24 \n매수 \n10,000원 \n6개월 \n-14.46% \n-7.70% \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Compliance Notice\n작성자(설용진)는 본 조사분석자료에 게재된 내용들이 본인의 의견을 정확하게 반영하고 있으며, 외부의 부당한 압력이나 간섭없이 신의성실하게 작성되었음을 확인합니다. \n본 보고서에 언급된 종목의 경우 당사 조사분석담당자는 본인의 담당종목을 보유하고 있지 않습니다. \n본 보고서는 기관투자가 또는 제 3 자에게 사전 제공된 사실이 없습니다. \n당사는 자료공표일 현재 해당기업과 관련하여 특별한 이해 관계가 없습니다. \n종목별 투자의견은 다음과 같습니다. \n투자판단 3 단계(6 개월기준) 15%이상 → 매수 / -15%~15% → 중립 / -15%미만 → 매도 \nSK 증권 유니버스 투자등급 비율 (2025 년 07 월 07 일 기준) \n매수 \n97.45% \n중립 \n2.55% \n매도 \n0.00% \n0\n5,000\n10,000\n15,000\n20,000\n25,000\n23.07\n23.10\n24.01\n24.04\n24.07\n24.10\n25.01\n25.04\n25.07\n미래에셋증권\n수정TP\n(원)'

# 무료버전인 Gemini 2.5 flash를 활용한 본문 정제

In [4]:
parser.paragraph

'미래에셋증권의 목표주가를 무위험수익률, 실적 추정치 조정 및 할인율 조정 등을 반영하여 18,000원으로 상향한다. 목표주가는 25E BVPS에 Target PBR을 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 등 영향으로 투자의견 중립을 제시한다.\n\n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려된다. 지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등에 대한 기대감은 제한적이라고 판단한다. 현재 밸류에이션이 정당화되기 위해서는 상대적으로 낮은 ROE 등 자본 활용의 효율성 측면의 제고가 필요하다고 판단한다.\n\n미래에셋증권의 2Q25 지배순이익은 컨센서스를 상회할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM 수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도 PF 수익 회복 등 영향으로 전분기 대비 개선되는 모습을 기대한다. 2Q25 기준 ROE 는 연율화 기준 약 9.1%를 전망한다.'

'미래에셋증권의 목표주가를 무위험수익률, 실적 추정치 조정 및 할인율 조정 등을 반영하여 18,000원으로 상향한다. 목표주가는 25E BVPS에 Target PBR을 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 등 영향으로 투자의견 중립을 제시한다.\n\n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려된다. 지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등에 대한 기대감은 제한적이라고 판단한다. 현재 밸류에이션이 정당화되기 위해서는 상대적으로 낮은 ROE 등 자본 활용의 효율성 측면의 제고가 필요하다고 판단한다.\n\n미래에셋증권의 2Q25 지배순이익은 컨센서스를 상회할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM 수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도 PF 수익 회복 등 영향으로 전분기 대비 개선되는 모습을 기대한다. 2Q25 기준 ROE 는 연율화 기준 약 9.1%를 전망한다.'

In [7]:
parser.raw_metadata

{'format': 'PDF 1.5',
 'title': '',
 'author': '',
 'subject': '',
 'keywords': '',
 'creator': 'Microsoft® Word 2016',
 'producer': 'Microsoft® Word 2016',
 'creationDate': "D:20250704170828+09'00'",
 'modDate': "D:20250704170828+09'00'",
 'trapped': '',
 'encryption': None}

In [8]:
parser.get_parsed_data()

{'title': '정상화된 이익 예상되나 다소 과도한 기대감',
 'firm': 'SK증권',
 'name': '미래에셋증권',
 'ticker': '006800',
 'ref_date': datetime.date(2025, 7, 4),
 'paragraph': '미래에셋증권의 목표주가를 무위험수익률, 실적 추정치 조정 및 할인율 조정 등을 반영하여 18,000원으로 상향한다. 목표주가는 25E BVPS에 Target PBR을 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 등 영향으로 투자의견 중립을 제시한다.\n\n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려된다. 지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등에 대한 기대감은 제한적이라고 판단한다. 현재 밸류에이션이 정당화되기 위해서는 상대적으로 낮은 ROE 등 자본 활용의 효율성 측면의 제고가 필요하다고 판단한다.\n\n미래에셋증권의 2Q25 지배순이익은 컨센서스를 상회할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM 수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도 PF 수익 회복 등 영향으로 전분기 대비 개선되는 

# 이미지 형태 보고서

In [11]:
parser = LlamaParser(pdf_path='/home/user/exercise_j/MiraeAsset/miraeasset2025/analyst_report/data/mirae_565749.pdf')

2025-07-26 15:45:21 - [INFO] [Step 23] 초기화 시작


In [12]:
parser.analyze()

2025-07-26 15:45:23 - [INFO] [Step 24] PDF 전체 분석 시작
2025-07-26 15:45:23 - [INFO] [Step 25] 본문 데이터 파싱 시작
2025-07-26 15:45:23 - [INFO] [Step 26] 본문 파싱 완료
2025-07-26 15:45:23 - [INFO] [Step 27] 텍스트 유효성 검증 시작
2025-07-26 15:45:23 - [WARNING] 의미 있는 컨텐츠가 부족하거나 이미지로 구성된 pdf입니다. LlamaParser를 호출합니다.
2025-07-26 15:45:23 - [INFO] [Step 28] LlamaParser 파싱 시작
2025-07-26 15:45:23 - [INFO] [Step 29] 메타데이터 파싱 시작
2025-07-26 15:45:23 - [INFO] [Step 30] 파싱 데이터 매핑 시작
2025-07-26 15:45:23 - [INFO] [Step 31] 첫 페이지 파싱 시작


Started parsing the file under job_id 2b068f52-401c-4623-8240-26a6c82931bf


메타데이터 파싱 중: 100%|██████████| 100/100 [00:03<00:00, 30.06it/s]
2025-07-26 15:45:39 - [INFO] [Step 32] 초기화 완료


Started parsing the file under job_id 55a98298-9211-4b43-bca1-4eab1a1271a2
....

본문 파싱 중: 100%|██████████| 100/100 [00:03<00:00, 30.06it/s]
2025-07-26 15:50:57 - [INFO] [Step 33] 파싱된 텍스트 처리 중
2025-07-26 15:50:57 - [INFO] [Step 34] LlamaParser 파싱 완료
2025-07-26 15:50:57 - [INFO] [Step 35] 본문 줄글 데이터 파싱 시작
2025-07-26 15:50:57 - [INFO] Initialized with 4 API keys, starting from index 0
2025-07-26 15:51:20 - [INFO] [Step 36] 분석 결과 요약
2025-07-26 15:51:20 - [INFO] [Step 37] 전체 분석 완료



PDF 분석 완료:
- 파일명: mirae_565749.pdf
- 추출된 텍스트 길이: 125자

분석된 내용:
- 종목명: 리가켐바이오
- 종목코드: 141080
- 작성날짜: 2024-10-25
- 증권사: 미래에셋증권


In [15]:
parser.raw_paragraph

"\nMIRAE ASSET 미래에셋증권\n\n# 리가켐바이오\n\n경쟁사의 악재, 리가켐에게 기회\n\n목표주가 17만원으로 상향, 투자 의견 매수 유지  \n리가켐바이오에 대한 투자 의견 매수를 유지하며, 목표주가를 170,000원(기존 86,000원)으로 상향한다. 목표주가는 6개의 상용 파이프라인 가치를 합산하여 SOTP로 산정하였다. 1) 기존 가시 성과에 반영되어 있던 파이프라인 6개 중 2조원에서 3.9조원으로 상향하였다. 2) 또한, 기존 리가켐바이오의 기업가치에 반영되지 않았던 3개(LCB97, LCB02A, LNCB74)의 파이프라인에 대한 가치를 1.8조원을 추가로 반영하였다. 오노약품과 팀을 통해 상용화 단계에 있는 파이프라인 또한 충분히 의미 있는 금액(약 1조원)이 될 가능성을 반영하였기 때문이다.\n\n## 리가켐바이오의 투자포인트\n\n1. 리가켐바이오는 더 이상 단순 플랫폼 기업이 아니다. 아직 상업화 아이템이 없으나, 오노약품, J&J, 암젠 등 글로벌 빅파마와 라이센스 계약을 체결하며 탄탄한 트랙레코드를 쌓고 있다. 단, ADC 기술의 조기상용화 가능성을 반영하여 LCB14(HER2 ADC) 중국 조건부승인으로 상향하였으며, 상용화 단계인 이뮤노젠(10억 달러로 인수)과 같은 기준으로 기업가치에 반영하여 기업가치를 보강.\n\n2. 최근 경쟁사의 악재로 ADC 경쟁력이 계속해서 임상에서 실패하고 있어 리가켐바이오의 Top2 ADC에 대한 기대가 높아지고 있다. 이로 인해 안헬의 옵션 행사 가능성이 높아졌다고 판단된다. 안헬의 옵션 행사 시점은 2025년으로 추정하였으며, 옵션행사로 2억 달러의 마일스톤이 유입될 수 있을 것으로 가정하였다.\n\n3. 빅파마들은 ADC 파이프라인을 더 도입하기 위해 오픈 있는 라이센스가 가능한 ADC 파이프라인의 수는 적었다. 이 또한 리가켐바이오의 기회가 된다. 글로벌 제약사가 M&A를 통해 ADC 기업을 인수하려고 시도했으나 조건부승인 ADC 기업이 거의 없기 때문이다. 상장된 기업을 기준으로

"\nMIRAE ASSET 미래에셋증권\n\n# 리가켐바이오\n\n경쟁사의 악재, 리가켐에게 기회\n\n목표주가 17만원으로 상향, 투자 의견 매수 유지  \n리가켐바이오에 대한 투자 의견 매수를 유지하며, 목표주가를 170,000원(기존 86,000원)으로 상향한다. 목표주가는 6개의 상용 파이프라인 가치를 합산하여 SOTP로 산정하였다. 1) 기존 가시 성과에 반영되어 있던 파이프라인 6개 중 2조원에서 3.9조원으로 상향하였다. 2) 또한, 기존 리가켐바이오의 기업가치에 반영되지 않았던 3개(LCB97, LCB02A, LNCB74)의 파이프라인에 대한 가치를 1.8조원을 추가로 반영하였다. 오노약품과 팀을 통해 상용화 단계에 있는 파이프라인 또한 충분히 의미 있는 금액(약 1조원)이 될 가능성을 반영하였기 때문이다.\n\n## 리가켐바이오의 투자포인트\n\n1. 리가켐바이오는 더 이상 단순 플랫폼 기업이 아니다. 아직 상업화 아이템이 없으나, 오노약품, J&J, 암젠 등 글로벌 빅파마와 라이센스 계약을 체결하며 탄탄한 트랙레코드를 쌓고 있다. 단, ADC 기술의 조기상용화 가능성을 반영하여 LCB14(HER2 ADC) 중국 조건부승인으로 상향하였으며, 상용화 단계인 이뮤노젠(10억 달러로 인수)과 같은 기준으로 기업가치에 반영하여 기업가치를 보강.\n\n2. 최근 경쟁사의 악재로 ADC 경쟁력이 계속해서 임상에서 실패하고 있어 리가켐바이오의 Top2 ADC에 대한 기대가 높아지고 있다. 이로 인해 안헬의 옵션 행사 가능성이 높아졌다고 판단된다. 안헬의 옵션 행사 시점은 2025년으로 추정하였으며, 옵션행사로 2억 달러의 마일스톤이 유입될 수 있을 것으로 가정하였다.\n\n3. 빅파마들은 ADC 파이프라인을 더 도입하기 위해 오픈 있는 라이센스가 가능한 ADC 파이프라인의 수는 적었다. 이 또한 리가켐바이오의 기회가 된다. 글로벌 제약사가 M&A를 통해 ADC 기업을 인수하려고 시도했으나 조건부승인 ADC 기업이 거의 없기 때문이다. 상장된 기업을 기준으로 다이이찌산쿄 다음으로 시가총액이 큰 기업은 리가켐바이오다. 글로벌 제약사들이 M&A를 통해 ADC 후보물질이 부족한 상황이다. ADC 치료제를 개발할 수 있는 곳은 여전히 적지만 공급이 부족해진 상황에서 기술력을 보유한 리가켐바이오의 수혜는 여전히 많아질 것으로 보인다.\n\n| 결산기 (12월) | 2022   | 2023E  | 2024E | 2025E | 2026E  |\n| --------- | ------ | ------ | ----- | ----- | ------ |\n| 매출액(억원)   | 0      | 0      | 234.1 | 197.1 | 0      |\n| 영업이익(억원)  | -151.5 | -283.2 | -38.4 | -59.1 | -234.1 |\n| 영업이익률 (%) | -      | -      | -16.4 | -30.0 | -      |\n| 순이익(억원)   | -151.5 | -283.2 | -38.4 | -59.1 | -234.1 |\n| EPS (원)   | -205.5 | -383.9 | -51.9 | -79.9 | -316.7 |\n| ROE (%)   | -20.5  | -35.1  | -4.3  | -6.4  | -      |\n| P/E (배)   | -      | -      | -     | -     | -      |\n| P/B (배)   | 10.4   | 10.4   | 10.4  | 10.4  | 10.4   |\n| 배당수익률 (%) | 0.0    | 0.0    | 0.0   | 0.0   | 0.0    |\n\n\n자료: 리가켐바이오, 미래에셋증권 리서치센터\n\n\n\n리거켐바이오\n\n# I. 기업가치\n\n리거켐바이오에 대한 투자의견 매수를 유지하며, 목표주가 170,000원으로 상향한다. 목표주가는 6개의 신약 파이프라인의 가치를 합산하여 SOTP로 산정하였다. 기존 기업 가치 산정에 반영하였던 파이프라인 가치를 2.6조원에서 3.9조원으로 상향하였으며, 새로운 파이프라인 LCB97, LCB02A, LNCB74의 가치 1.8조원을 추가로 반영하였다. 영구성장률 3%, 가중평균자본비용(WACC) 8.2%를 적용하였다.\n\n## 1. 기존 파이프라인 가치 상향(2조 5,561억원 → 3조 8,760억원)\n\n① **LCB14(HER2 ADC):** 신약가치는 1조 3,281억원으로 기존 8,171억원 대비 5,110억원을 추가로 반영하였다. 포스파젠(중국)과 약수다에 기술이전된 LCB14(HER2 ADC)는 2025년 중국(조건부 승인), 2028년 미국에 출시되면서 매출에 따라 로열티가 유입될 것으로 가정하였다. 최대 매출은 35억 7,800만 달러로 예측하였고 유입률은 20%를 가정하였다. 임상 성공확률은 기존 30%에서 50%로 상향하였다. 내년 중국 조건부 승인으로 인한 상업화가 기대되기 때문이다.\n\n② **LCB84(Trop 2 ADC):** 신약가치는 1조 7,891억원으로 기존 1조 6,491억원 대비 소폭 증가하였다. 이는 LCB84의 타깃 시장을 기존 트리플 및 Dato-Dxd 시장에서 폐암 및 삼중음성유방암 시장으로 변경하여 조정된 것이다. 임상 성공확률은 30%로 유지하였다.\n\nLCB84는 완전히 기술이전된 파이프라인이다. 임상 2상 이전인 2025년 시점 안에서 옵션을 행사하면서 옵션 행사금 2억 달러가 유입될 수 있을 것으로 가정하였다. 최근 경쟁력의 임상 실패로 안센의 옵션 행사 가능성이 높아졌다고 판단하였다. 상업화 이후에는 15%의 로열티가 유입될 것으로 가정하였다.\n\n③ **LCB71(ROR1 ADC):** 신약가치는 7,588억원으로 기존 902억원 대비 8.4배 증가되었다. 기존에는 ROR1 ADC가 타깃할 수 있는 시장을 호지킨 림프종 시장으로 제한적으로 가정하였다. 하지만 1) 호지킨 림프종 뿐만 아니라 미만성 거대B세포 림프종 및 고형암에서도 암세포의 반응율이 관찰되었다. 2) 또한, LCB71(CS5001)의 파트너사인 시스톤 파마슈티컬스(CStone Pharmaceuticals)는 고형암과 혈액암 모두에서 Dose Level 9까지도 독성이 나타나지 않았음을 발표하였다. 좋은 효능 및 안전성이 대한 데이터가 확인되고 있다. 따라서, 독성이 매우 강한 페이로드임에도 신약으로써의 기능이 높아지고 있다고 판단하였다.\n\n임상 1상 중인 LCB71(ROR71 ADC)도 2030년 호지킨 및 비호지킨 림프종치료제로 미국 출시 가능한 것으로 전망하였다. 미국 출시 후 시스톤 파마슈티컬스로부터 로열티 15%가 유입될 수 있을 것으로 가정하였다. 임상 성공확률은 30%로 가정하였다.\n\n2 Mirae Asset Securities Research\n\n\n\n리거펜바이오\n\n# 2. LCB97, LCB02A, LNCB74 파이프라인 가치 반영(1조 7,784억원)\n\n10월 10일, 오노약품과 딜을 통해 전임상 단계에 있는 파이프라인 또한 충분히 의미 있는 금액(약 1조원)의 딜이 가능해진 상황으로 판단하였다. 따라서 기존 리거펜바이오의 기업가치에 반영하지 않았던 3개의 파이프라인에 대한 신약가치를 추정 및 반영하였다.\n\n④ **LCB97(LC1AM ADC):** 신약가치는 8,197억원으로 반영하였다. LCB97은 LC1AM을 타깃으로 하는 ADC로, ADC 타깃 중 노블(novel)한 타깃이다. 타깃 적응증은 전임상 결과가 확보되어있는 폐암과 삼중음성유방암으로 적용하였다. 점유율은 시장 출시 시점으로 예상되는 2031년 0.5%를 시작으로 출시 6년차 시장 5% 점유율이 가능한 것으로 전하였다. 로열티는 판매금액의 15%로 가정하였으며, 마일스톤 단계별 4.5억 달러가 유입될 것으로 가정하였다. 전임상 단계임을 고려하여 성공확률은 5%로 가정하였다.\n\n⑤ **LCB02A(Claudin18.2 ADC):** 신약가치는 2,840억원으로 반영하였다. LCB02A는 Claudin18.2을 타깃으로하며 토모다이나스메이틱스를 페이로드로 사용한다. 타깃과 페이로드 모두 많은 ADC 후보물질의 임상이 진행되고 있어 글로벌 제약사의 관심이 높다.\n\n적응증은 전임상 결과에서 효과를 보였던 위암과 췌장암으로 적용하였다. 점유율은 시장 출시 시점으로 예상되는 2031년 0.5%를 시작으로 출시 6년차 시장 5% 점유율이 가능한 것으로 전하였다. 전임상 단계임을 고려하여 성공확률은 7%로 가정하였다.\n\n참고로, 23년 2월, 아스트라제네카는 KYMH이와이언스로부터 Claudin18.2 ADC 제제 CMG901의 라이선스를 임상 1상 단계에서 12억 달러에 도입하였다. 23년 10월에는 독일 머크가 항체자유로부터 Claudin18.2 ADC(SHR-A1904)를 포함한 총 2개의 파이프라인의 권리(중국 제외)를 1억 달러에 계약하였다.\n\n⑥ **LNCB74(B7-H4 ADC):** 신약가치는 6,747억원으로 반영하였다. LCB97은 B7-H4을 타깃으로 하는 ADC로, 페이로드는 LCB84(Trop 2 ADC)와 동일한 MMAE를 사용한다. B7-H4는 ADC 임상 후보물질의 타깃 중 선폐포 많이 연구되고 있는 타깃이다. 타깃 적응증은 B7-H4가 많이 발현되는 것으로 알려진 양성인 유방암, 난소암, 자궁암으로 적용하였다. 점유율은 시장 출시 시점으로 예상되는 2031년 0.5%를 시작으로 출시 6년차 시장 5% 점유율이 가능한 것으로 전하였다. 전임상 단계임을 고려하여 성공확률은 5%로 가정하였다.\n\nMirae Asset Securities Research 3\n\n\n리거켐바이오 2024.10.25\n\n리거켐바이오의 기업가치는 23년 11월 애브비에 인수된 이뮤노젠(101억 달러)과 24년 초 젠맵에 인수되었던 프로파일온드바이오(18억 달러) 사이에 위치하고 있다고 판단된다. 리거켐바이오는 아직 상업화된 파이프라인이 없기 때문이다.\n\n반면, 이뮤노젠은 101억 달러에 인수되었으며 ADC 상업화 아이템 엘러히얼을 보유하고 있었다. 프로파일온드바이오는 18억 달러에 인수되었는데 가장 빠른 파이프라인은 임상 1/2상단계였으며, 상업화 파이프라인은 없었다.\n\n하지만, 리거켐바이오는 오노약품, J&J, 암젠 등 글로벌 빅파마와 라이선스 계약을 체결하며 단단한 트랙 레코드를 쌓고 있다. 상업화 아이템이 없으나, 타 ADC 기업들과 차별화될 수 있는 포인트이다. 만약 2025년 LCB14(HER2 ADC) 중국 조건부승인을 상업화 아이템까지 등장한다면 이뮤노젠과 같은 기준으로 기업가치 판단이 가능할 것으로 보인다.\n\n| 표 1. 리거켐바이오의 기술이전 계약 현황<br/>플랫폼 | 표 1. 리거켐바이오의 기술이전 계약 현황<br/>날짜 | 표 1. 리거켐바이오의 기술이전 계약 현황<br/>파트너 | 표 1. 리거켐바이오의 기술이전 계약 현황<br/>파이프라인 | 표 1. 리거켐바이오의 기술이전 계약 현황<br/>총 마일스톤 (억원) |\n| ------------------------------- | ------------------------------ | ------------------------------- | --------------------------------- | --------------------------------------- |\n| 후보물질                            | 2015.08                        | Fosun Pharma                    | LCB14(HER2-MMAF)                  | 2,784                                   |\n|                                 | 2020.05                        | ISUDEA                          | LCB73(CD19-pBD)                   | 2,784                                   |\n|                                 | 2020.05                        | CSTONE                          | LCB71(RO1-pPBD)                   | 4,099                                   |\n|                                 | 2020.12                        | PYXIS                           | LCB67(LIV1-MMAE)                  | 3,255                                   |\n|                                 | 2021.12                        | ISUDEA                          | LCB14(HER2-MMAF)                  | 11,864                                  |\n| ADC                             | 2023.12                        | Janssen                         | LCB84(Trop2-MMAE)                 | 3,284                                   |\n|                                 | 2024.10                        | ONO PHARMACEUTICAL              | LCB97(1CAM-ADC)                   | 4,343                                   |\n|                                 | 2023.10                        | Takeda                          | ADC platform(3개 대체 linker)        | 5,494                                   |\n|                                 | 2021.06                        | ISUDEA                          | ADC platform(6개 대체 linker/toxin)  | 5,494                                   |\n|                                 | 2021.10                        | SOTIO Biotech                   | ADC platform(5개)                  | 12,127                                  |\n|                                 | 2022.12                        | Amgen                           | ADC platform(5개)                  | 16,050                                  |\n|                                 | 2024.10                        | ONO PHARMACEUTICAL              | ADC platform(비공개)                 | 비공개                                     |\n|                                 | 2009.06                        | GC녹십자/Leo's Pharma              | Nokxaban                          | 비공개                                     |\n|                                 | 2016.12                        | 한미바이오                           | Delpazoidol                       | 240                                     |\n|                                 | 2017.05                        | 브릭스바이오테라퓨틱스                     | BBT-877                           | 300                                     |\n\n\n자료: 리거켐바이오, 미래에셋증권 리서치센터\n\n| 표 2. 리거켐바이오 목표주가 산정<br/>내용 | 표 2. 리거켐바이오 목표주가 산정<br/>금액 (십억원) | 표 2. 리거켐바이오 목표주가 산정<br/>비고 |\n| -------------------------- | -------------------------------- | -------------------------- |\n| 산업가치                       | 5,654                            |                            |\n| LCB14(HER2-MMAF)           | 1,328                            | 기존 817                     |\n| LCB84(Trop2-MMAE)          | 1,789                            | 기존 1,649                   |\n| LCB71(RO1-pPBD)            | 759                              | 기존 90                      |\n| LCB97(1CAM ADC)            | 320                              | 신규 반영                      |\n| LCB202(Claudin18.2 ADC)    | 294                              | 신규 반영                      |\n| LNCB74(87-1H4 ADC)         | 2,164                            | 신규 반영                      |\n| 순차입금                       | (580)                            |                            |\n| 주주가치                       | 6,235                            |                            |\n| 발행주식 수(추정)                 | 36,428                           |                            |\n| 적정주가                       | 171,147                          |                            |\n| 목표주가                       | 170,000                          |                            |\n\n\n자료: 미래에셋증권 리서치센터\n\n4 Mirae Asset Securities Research\n\n\n리거버이오\n\n# 표 3. LCB14(HER2 ADC) 가치\n\n(백만 달러)\n\n|                | 2023 | 24F  | 25F  | 26F  | 27F  | 28F  | 29F  | 30F  | 31F  | 32F  | 33F  | 34F  |\n|----------------|------|------|------|------|------|------|------|------|------|------|------|------|\n| 시장규모       | 3,426| 4,813| 6,738| 8,943| 10,483| 12,146| 14,018| 14,719| 15,465| 16,228| 17,039| 17,891|\n| 성장률(%)      | 40%  | 40%  | 33%  | 17%  | 16%  | 15%  | 5%   | 5%   | 5%   | 5%   | 5%   | 5%   |\n| M/S            |      | 1%   | 1%   | 2%   | 5%   | 10%  | 15%  | 20%  | 20%  | 20%  | 20%  | 20%  |\n| 임상현황       |      |      |      |      |      |      |      |      |      |      |      |      |\n| 에상매출       | 34   | 89   | 210  | 607  | 1,402| 2,208| 3,091| 3,246| 3,408| 3,578|      |      |\n| 로열티(10% 가정)| 3   | 9    | 21   | 61   | 140  | 221  | 309  | 325  | 341  | 358  |      |      |\n| FCF            |      | 3    | 7    | 49   | 112  | 177  | 247  | 260  | 273  | 286  |      |      |\n| NPV            |      | 2    | 6    | 13   | 35   | 76   | 110  | 142  | 138  | 134  | 130  |      |\n\n- Terminal Value: 2,578\n- PV of Terminal value: 1,172\n- 합산 수익: 1,960\n- Risk-adjusted NPV: 980\n\n자료: 미래에셋증권 리서치센터\n\n# 표 4. LCB84(Trop2 ADC) 가치\n\n(백만 달러)\n\n|                | 2023   | 24F   | 25F   | 26F   | 27F   | 28F   | 29F   | 30F   | 31F   | 32F   | 33F   | 34F   |\n|----------------|--------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|\n| 시장규모(폐암+삼중음성유방암) | 61,923 | 70,547| 79,234| 87,725| 96,155| 102,973| 111,028| 119,479| 128,443| 138,106| 148,525| 159,761|\n| 폐암           | 31,630 | 35,843| 38,922| 41,902| 46,314| 50,384| 54,794| 59,837| 65,222| 71,092| 77,491| 84,465|\n| 삼중음성유방암 | 30,293 | 34,704| 40,312| 45,823| 49,841| 52,589| 56,234| 59,642| 63,221| 67,014| 71,035| 75,297|\n| 성장률(%)      | 14%    | 12%   | 11%   | 10%   | 7%    | 7%    | 8%    | 8%    | 8%    | 8%    | 8%    | 8%    |\n| M/S            |        | 1%    | 1%    | 2%    | 3%    | 3%    | 3%    | 3%    | 3%    | 3%    | 3%    | 3%    |\n| 임상현황       |        | 1상 개시| 1상 종료| 2상 개시| 2상 종료| 3상 개시| 3상 종료| 3상 개시| 3상 종료| FDA 허가|       |       |\n| 예상매출       |        | 80    | 220   | 200   | 300   | 623   | 2,390 | 3,211 | 4,143 | 4,456 | 4,793 |       |\n| 로열티(15% 가정)|        | 358   | 321   | 414   | 446   | 479   |       |       |       |       |       |       |\n| 마일스톤       |        | 80    | 220   | 200   | 300   | 623   |       |       |       |       |       |       |\n| FCF            |        | 64    | 176   | 160   | 240   | 785   | 257   | 331   | 356   | 383   |       |       |\n| NPV            |        | 64    | 163   | 126   | 162   | 489   | 148   | 176   | 175   | 174   |       |       |\n\n- Terminal Value: 3,453\n- PV of Terminal value: 2,570\n- 합산 수익: 4,248\n- Risk-adjusted NPV: 1,274\n\n자료: 미래에셋증권 리서치센터\n\nMirae Asset Securities Research 5\n\n\n리카벰바이오\n\n# 표 5. LCB71(ROR1 ADC) 가치\n\n(백만 달러)\n\n|        | 2023  | 24F   | 25F   | 26F   | 27F   | 28F   | 29F   | 30F   | 31F   | 32F   | 33F   | 34F   |\n|--------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|\n| 시장규모(호지킨/비호지킨 림프종) | 15,444 | 15,538 | 17,239 | 18,799 | 21,431 | 24,405 | 28,014 | 31,852 | 36,630 | 42,124 | 48,443 | 55,709 |\n| 호지킨 림프종                  | 1,405  | 1,403  | 1,491  | 1,549  | 1,575  | 1,505  | 1,595  | 1,630  | 1,875  | 2,156  | 2,479  | 2,851  |\n| 비호지킨 림프종                | 14,039 | 14,135 | 15,748 | 17,250 | 19,856 | 22,810 | 26,419 | 30,222 | 34,755 | 39,969 | 45,964 | 52,858 |\n\n| 성장률(%) | 1% | 11% | 9% | 14% | 14% | 15% | 14% | 15% | 15% | 15% | 15% | 15% |\n| M/S      |    |     |    |     |     |     | 2%  | 3%  | 3%  | 3%  | 3%  | 5%  |\n\n| 임상현황 | 2상 개시 | 2상 종료 | 3상 종료 | FDA 허가 | | | | | |\n|----------|----------|----------|----------|----------|---|---|---|---|---|\n| 예상매출 |          |          |          |          | | | | | |\n| 로열티(15% 가정) |          |          |          | 637  | 916  | 1,264 | 1,453 | 2,785 | |\n| 마일스톤 |          |          | 150      | 204      | 96   | 137  | 190  | 218  | 418  |\n| FCF      |          |          | 120      | 163      | 76   | 110  | 152  | 174  | 334  |\n| NPV      |          |          | 103      |          | 48   | 63   | 81   | 86   | 152  |\n\n| Terminal Value | 3,011 |\n|----------------|-------|\n| PV of Terminal value | 1,369 |\n| 현재 수익 | 1,901 |\n| Risk-adjusted NPV | 570 |\n\n자료: 미래에셋증권 리서치센터\n\n# 표 6. LCB97(LCAM ADC) 가치\n\n(백만 달러)\n\n|        | 2023  | 24F   | 25F   | 26F   | 27F   | 28F   | 29F   | 30F   | 31F   | 32F   | 33F   | 34F   |\n|--------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|\n| 시장규모(폐암/상동종유방암) | 61,923 | 70,547 | 79,234 | 87,725 | 96,155 | 102,973 | 111,028 | 119,479 | 128,443 | 138,106 | 148,525 | 159,761 |\n| 폐암                        | 31,630 | 35,843 | 38,922 | 41,092 | 46,314 | 50,384  | 54,794  | 59,837  | 65,222  | 71,092  | 77,491  | 84,265  |\n| 상동종유방암                | 30,293 | 34,704 | 40,312 | 45,823 | 49,841 | 52,589  | 56,234  | 59,642  | 63,221  | 67,014  | 71,035  | 75,297  |\n\n| 성장률(%) | 14% | 12% | 11% | 10% | 7% | 8% | 10% | 9% | 10% | 10% | 10% | 10% |\n| M/S      |     |     |     |     |    |    | 1%  | 2% | 2%  | 2%  | 3%  | 3%  |\n\n| 임상현황 | 1상 개시 | 1상 종료 | 2상 개시 | 2상 종료 | 3상 개시 | 3상 종료 | FDA 허가 | | | |\n|----------|----------|----------|----------|----------|----------|----------|----------|---|---|---|\n| 예상매출 |          |          |          |          |          |          | 642  | 2,072 | 4,456 | 4,793 |\n| 로열티(15% 가정) |          |          |          |          |          |          | 96   | 311  | 668  | 719  |\n| 마일스톤 |          |          | 100      | 150      | 200      |          |          | | | |\n| FCF      |          |          | 80       | 120      | 160      | 77       | 249  | 535  | 575  | |\n| NPV      |          |          | 68       | 100      | 44       | 132      | 263  | 262  | | |\n\n| Terminal Value | 5,180 |\n|----------------|-------|\n| PV of Terminal value | 5,180 |\n| 현재 수익 | 6,049 |\n| Risk-adjusted NPV | 605 |\n\n자료: 미래에셋증권 리서치센터\n\n6 Mirae Asset Securities Research\n\n\n리카벵바이오\n\n# 표 7. LCB02A(Claudin18.2 ADC) 가치\n\n(백만 달러)\n\n|        | 2023 | 24F  | 25F  | 26F  | 27F  | 28F  | 29F  | 30F  | 31F  | 32F  | 33F  | 34F   |\n|--------|------|------|------|------|------|------|------|------|------|------|------|-------|\n| 시장규모(위암+췌장암) | 1,786 | 2,043 | 2,335 | 2,891 | 3,459 | 4,670 | 5,870 | 7,290 | 8,903 | 9,458 | 10,774 | 12,275 |\n| 위암   | 1,468 | 1,661 | 1,904 | 2,296 | 2,659 | 3,075 | 3,539 | 4,012 | 4,534 | 5,123 | 5,789 | 6,541  |\n| 췌장암 | 318  | 382  | 431  | 595  | 800  | 1,595 | 2,331 | 3,278 | 3,770 | 4,335 | 4,985 | 5,733  |\n\n| 성장률(%) |      | 14%  | 17%  | 21%  | 20%  | 35%  | 26%  | 24%  | 14%  | 14%  | 14%  | 14%   |\n|----------|------|------|------|------|------|------|------|------|------|------|------|-------|\n| M/S      |      | 1차 개시 | 1차 종료 | 2차 개시 | 2차 종료 | 3차 개시 | 3차 종료 FDA 허가 |      |      |      |      | |\n|          |      | 1%   | 2%   | 3%   | 3%   |      |      |      |      |      |      |       |\n\n| 예측매출 |      |      |      |      |      |      |      |      |      |      |      |       |\n| FCF      |      | 42   | 142  | 323  | 368  |      |      |      |      |      |      |       |\n| NPV      |      | 33   | 113  | 259  | 295  |      |      |      |      |      |      |       |\n\n|          |      |      |      |      |      |      |      |      |      |      |      |       |\n| Terminal Value | 2,653 |      |      |      |      |      |      |      |      |      |      |       |\n| PV of Terminal value | 2,653 |      |      |      |      |      |      |      |      |      |      |       |\n| 할인 수익 | 2,994 |      |      |      |      |      |      |      |      |      |      |       |\n| Risk-adjusted NPV | 210  |      |      |      |      |      |      |      |      |      |      |       |\n\n자료: 미래에셋증권 리서치센터\n\n# 표 8. LNCB74(B7–H4 ADC) 가치\n\n(백만 달러)\n\n|        | 2023 | 24F  | 25F  | 26F  | 27F  | 28F  | 29F  | 30F  | 31F  | 32F  | 33F  | 34F   |\n|--------|------|------|------|------|------|------|------|------|------|------|------|-------|\n| 시장규모(유방암+난소암+자궁암) | 34,098 | 39,388 | 46,508 | 52,748 | 57,466 | 60,867 | 65,104 | 69,323 | 73,613 | 78,172 | 83,016 | 88,163 |\n| 유방암 | 30,293 | 34,704 | 40,312 | 45,823 | 49,841 | 52,589 | 56,234 | 59,624 | 63,621 | 67,014 | 71,035 | 75,297  |\n| 난소암 | 3,096 | 3,444 | 4,646 | 5,173 | 5,790 | 6,341 | 6,862 | 7,582 | 8,189 | 8,844 | 9,551 | 10,315  |\n| 자궁암 | 709  | 1,240 | 1,550 | 1,752 | 1,835 | 1,937 | 2,008 | 2,099 | 2,204 | 2,314 | 2,430 | 2,551  |\n\n| 성장률(%) |      | 16%  | 18%  | 13%  | 9%   | 6%   | 7%   | 6%   | 6%   | 6%   | 6%   | 6%    |\n|----------|------|------|------|------|------|------|------|------|------|------|------|-------|\n| M/S      |      | 1차 개시 | 1차 종료 | 2차 개시 | 2차 종료 | 3차 개시 | 3차 종료 FDA 허가 |      |      |      |      | |\n|          |      | 1%   | 2%   | 3%   | 3%   |      |      |      |      |      |      |       |\n\n| 예측매출 |      |      |      |      |      |      |      |      |      |      |      |       |\n| FCF      |      | 368  | 1,173 | 2,490 | 2,645 |      |      |      |      |      |      |       |\n| NPV      |      | 294.5 | 938.1 | 1,992.4 | 2,115.9 |      |      |      |      |      |      |       |\n\n|          |      |      |      |      |      |      |      |      |      |      |      |       |\n| Terminal Value | 19,057 |      |      |      |      |      |      |      |      |      |      |       |\n| PV of Terminal value | 7,347 |      |      |      |      |      |      |      |      |      |      |       |\n| 할인 수익 | 9,959 |      |      |      |      |      |      |      |      |      |      |       |\n| Risk-adjusted NPV | 498  |      |      |      |      |      |      |      |      |      |      |       |\n\n자료: 미래에셋증권 리서치센터\n\nMirae Asset Securities Research 7\n\n\n\n리카바이오\n\n# 표 9. ADC 관련 기업 밸류에이션\n\n| 기업명<br/>ADC THERAPEUTICS | 에이디씨테라퓨틱스<br/>ADCT US | 에이디씨테라퓨틱스<br/>4568 JP | 다이이찌산쿄<br/>PYXS US | 픽시스 온콜로지<br/>MRSN US | 메르사나 테라퓨틱스<br/>141080 KS | 리카겐바이오 |\n| ------------------------ | --------------------- | --------------------- | ------------------ | -------------------- | ------------------------ | ------ |\n| 시가총액(백만 달러)              | 311                   | 64,033                | 196                | 259                  | 4,406                    |        |\n| 2023                     |                       |                       |                    |                      |                          |        |\n| 매출액(백만달러, 십억원)           | 70                    | 11,093                | 37                 | 34                   |                          |        |\n| 영업이익(백만달러, 십억원)          | -166                  | 1,465                 | -82                | -180                 | -81                      |        |\n| EBITDA(백만달러, 십억원)        | -165                  | 1,879                 | -78                | -174                 | -76                      |        |\n| 순이익(백만달러, 십억원)           | -240                  | 1,390                 | -74                | -172                 | -74                      |        |\n| EPS(달러, 원)               | -3                    | 1                     | -2                 | -1                   | -2,595                   |        |\n| PER(배)                   |                       | 46                    |                    |                      |                          |        |\n| PBR(배)                   |                       | 5                     |                    | 8                    | 12                       |        |\n| ROE(%)                   |                       | 13                    |                    | -52                  | -266                     | -40    |\n| EV/EBITDA(배)             |                       | 30                    |                    |                      | 7                        | 54     |\n| PSR(배)                   | 2                     | 6                     |                    | 7                    | 54                       |        |\n| 2024F                    |                       |                       |                    |                      |                          |        |\n| 매출액(백만달러, 십억원)           | 73                    | 12,162                | 16                 | 25                   | 130                      |        |\n| 영업이익(백만달러, 십억원)          | -128                  | 1,684                 | -70                | -91                  | -11                      |        |\n| EBITDA(백만달러, 십억원)        | -114                  | 2,102                 |                    | -95                  | -6                       |        |\n| 순이익(백만달러, 십억원)           | -159                  | 1,421                 | -63                | -88                  | 6                        |        |\n| EPS(달러, 원)               | -2                    | 1                     | -1                 | -1                   | 287                      |        |\n| PER(배)                   |                       | 44                    |                    |                      | 420                      |        |\n| PBR(배)                   |                       | 6                     |                    |                      | 7                        |        |\n| ROE(%)                   | 81                    | 13                    |                    | -1,072               | 1                        |        |\n| EV/EBITDA(배)             |                       | 28                    |                    |                      |                          |        |\n| PSR(배)                   | 4                     | 5                     | 12                 | 10                   | 34                       |        |\n| 2025F                    |                       |                       |                    |                      |                          |        |\n| 매출액(백만달러, 십억원)           | 84                    | 14,044                |                    | 33                   | 204                      |        |\n| 영업이익(백만달러, 십억원)          | -135                  | 2,144                 | -96                | -98                  | 49                       |        |\n| EBITDA(백만달러, 십억원)        | -96                   | 2,611                 |                    | -95                  | 54                       |        |\n| 순이익(백만달러, 십억원)           | -160                  | 1,753                 | -91                | -96                  | 58                       |        |\n| EPS(달러, 원)               | -1                    | 1                     | -1                 | -1                   | 1,279                    |        |\n| PER(배)                   |                       | 35                    |                    |                      | 94                       |        |\n| PBR(배)                   |                       | 5                     |                    |                      | 6                        |        |\n| ROE(%)                   | 62                    | 15                    |                    | -124                 | 8                        |        |\n| EV/EBITDA(배)             |                       | 23                    |                    |                      | 72                       |        |\n| PSR(배)                   | 4                     | 5                     |                    | 8                    | 22                       |        |\n\n\n주: 2024년 10월 17일 기준  \n자료: 블룸버그, 미래에셋증권 리서치센터\n\n8 Mirae Asset Securities Research\n\n\n\n리거켐바이오\n\n# II. 투자포인트\n\n## 1. Trop2 ADC의 가치는 높아지는 중\n\nTrop2 ADC 경쟁약물이 계속해서 임상에서 실패하면서 리거켐바이오의 Trop2 ADC에 대한 기대가 높아지고 있다. 1) 길리어드의 트로델비 및 다이이찌산쿄의 Dato-Dxd의 임상 3상 실패로, 동일 적응증에서 임상 성공 시, 경쟁 약물 대비 높은 매출액 달성이 가능할 것으로 보인다. 2) 이로 인해 안테임 옵션 행사 가능성이 높아졌다고 판단된다. 안테임 옵션 행사 시점은 2025년으로 추정하였으며, 옵션행사로 2억 달러의 마일스톤이 유입될 수 있을 것으로 가정하였다.\n\n### 1) 경쟁약물들의 임상 실패(트로델비와 Dato-Dxd)\n\n폐암은 TROP2 ADC를 가지고 있는 기업이 좋은 데이터를 얻고 싶어하는 적응증이다. 2020년 FDA 허가를 받은 길리어드의 트로델비가 2년 1일 비소세포폐암 환자 전체생존율 연장에 실패하였기 때문이다. EVOKE-01에서 트로델비의 전체 생존율은 11.9개월으로 대조군인 Docetaxel 8.9개월 대비 통계적 유의미성을 확보하지 못하였다.\n\n다이이찌산쿄의 Dato-Dxd도 비소세포폐암 적응증에서의 객관적 반응율이 펨브롤리주맙에 대한 결과는 좋지 않았다. 2024년 2월 내평가 비소세포폐암 2차 치료제로만 허가 신청을 완료(국가 2월, 유럽 3월)하였다. 하지만, 최근 전체생존율(OS) 데이터도 12.9개월(vs. 18개월)을 발표하며 통계적 유의성을 확보하지 못하였다.\n\nLCB84는 Trop2 항체에 MMAE(모노메틸 오리스타틴 E; monomethyl auristatin E) 페이로드, 리거켐바이오의 링커로 구성되어있다. 출처된 길리어드의 트로델비는 SN-38의 캠토테신 계열 토포이소머레이즈 저해제를 이용한다. 다이이찌산쿄의 Dato-Dxd도 토포이소머레이즈 저해제이다. 리거켐바이오가 사용하는 페이로드인 MMAE의 독성이 트로델비 및 Dato-Dxd의 페이로드보다 독성이 더 높다. 높은 효율을 기대할 수 있으나 정상세포에 페이로드가 작용했을 때 부작용 문제가 생길 수 있다. 따라서 LCB84 임상 1상에서 안정성 결과가 매우 중요하다.\n\n안정성 결과가 잘 나온다면 이후 트로델비와 Dato-Dxd가 실패한 폐암 적응증에서의 임상 성공에 대한 기대감이 높아질 것으로 보인다. 리거켐바이오의 Trop2 ADC(LCB84)는 2023년 12월 임상 1상 첫환자 투여가 완료예정이다. 또한 기술이전 안테임 2.2조원의 기술이전 되었다. 계약금 1,300억원이 유입되었으며, 1/2상 중 안테임 옵션을 행사하면 마일스톤 수취도 가능하다.\n\nMirae Asset Securities Research\n\n\n\n리거켐바이오\n\n# 그림 1. Trop2 타깃 치료제의 기전\n\n!Trop2 타깃 치료제의 기전\n\n출처: Pharmacology & Therapeutics(2022), 미래에셋증권 리서치센터\n\n# 그림 2. LCB84(TROP2–MMAE) 효과(비소세포폐암)\n\n!LCB84(TROP2–MMAE) 효과(비소세포폐암)\n\n출처: 리거켐바이오, 미래에셋증권 리서치센터\n\n# 그림 3. LCB84(TROP2–MMAE) 효과(비소세포폐암)\n\n!LCB84(TROP2–MMAE) 효과(비소세포폐암)\n\n출처: 리거켐바이오, 미래에셋증권 리서치센터\n\n# 표 10. Trop2 ADC 임상 실패\n\n| 기업          | 시기      | 파이프라인명   | 임상단계  | 적응증                     | 실패요인                                              |\n| ----------- | ------- | -------- | ----- | ----------------------- | ------------------------------------------------- |\n| 길리어드/이뮤노메딕스 | 2024.01 | 트로델비     | 임상 3상 | NSCLC                   | OS 개선 실패, 화학요법군보다 트로델비 투여군이 오래 살았으나 통계적 유의성 입증 실패 |\n|             | 2024.05 |          | 임상 3상 | mUC                     | OS 달성 실패, 중증간 감소증 합병증 관련 부작용                      |\n| A/Z/다이이찌산쿄  | 2022.09 | Dato-dxd | 임상 3상 | HER2-low 또는 HER2-음성 유방암 | OS 개선 실패                                          |\n|             | 2024.09 |          | 임상 3상 | NSCLC                   | OS 개선 실패, 통계적 유의성 확보 실패                           |\n\n\n출처: 각사, 미래에셋증권 리서치센터\n\n10 Mirae Asset Securities Research\n\n\n\n리거셉바이오\n\n# 그림 4. Dato-Dxd의 비소세포폐암(TROPION–Lung01) 임상 결과: PFS 0.7개월 개선\n\n!Graph 4\n\n| Median (95% CI), months | Data-DXd      | Docetaxel |\n| ----------------------- | ------------- | --------- |\n| 4.4 (4.2-5.6)           | 3.7 (2.9-4.2) |           |\n\n\n| HR               | P-value | Prespecified boundary (2-sided) |\n| ---------------- | ------- | ------------------------------- |\n| 0.74 (0.58-0.93) | 0.007   | 0.4                             |\n\n\n| ORR (95% CI), %  | Data-DXd | Docetaxel |\n| ---------------- | -------- | --------- |\n| 28.4 (21.5-31.8) | 10.3     |           |\n\n\n| DOR (95% CI), mo | Data-DXd      | Docetaxel |\n| ---------------- | ------------- | --------- |\n| 7.1 (5.1-6.6)    | 5.6 (5.4-7.1) |           |\n\n\n출처: 다이애미쓰코, 미래에셋증권 리서치센터\n\n# 그림 5. Dato–Dxd의 비편평 비소세포폐암(TROPION–Lung01) 임상 결과: PFS 1.9개월 개선\n\n!Graph 5\n\n| Median (95% CI), months | Data-DXd      | Docetaxel |\n| ----------------------- | ------------- | --------- |\n| 5.6 (4.4-7.0)           | 3.7 (2.9-4.2) |           |\n\n\n| HR               | ORR, % | DOR, months |\n| ---------------- | ------ | ----------- |\n| 0.83 (0.51-0.79) | 31.2   | 12.8        |\n|                  | 7.7    | 5.6         |\n\n\n출처: 다이애미쓰코, 미래에셋증권 리서치센터\n\nMirae Asset Securities Research 11\n\n\n\n리게백바이오\n\n# 2. ROR1에 가치를 줘야할 때\n\nROR1 ADC(LCB71)에 대한 신약가치를 기존 902억원에서 7,588억원으로 상향하였다. 기존에는 ROR1 ADC가 타깃할 수 있는 시장을 호지킨 림프종 시장으로 제한적으로 보았다. 하지만 1) 호지킨 림프종 뿐만 아니라 미만성 거대B세포 림프종 및 고형암에서도 암세포의 반응을 관찰하였다. 2) 또한, LCB71(CS5001)의 파트너사인 시스톤 파마슈티컬스(CStone Pharmaceuticals)는 고형암과 혈액암 모두에서 Dose Level 9까지도 독성이 나타나지 않음을 발표하였다. 좋은 효능 및 안정성이 데이터가 확인되고 있어, 독성이 매우 강한 페이로드임에도 신약으로써의 가능성이 높아지고 있다고 판단하였다. 12월 ASH를 통해 추가 데이터를 발표할 예정이며, 2025년 임상 1b/2상이 개시될 것으로 예상된다.\n\n참고로 24년 4월 입센은 스트로바이오파마의 STRO-003(ROR1 ADC)를 전임상 단계에서 총 9억 달러에 기술 도입했다. 또한, 머크도 2020년 ROR1 ADC(임상 2상 이후) 파이프라인을 보유한 벨로스 바이오를 27.5억 달러에 인수하였다. ROR1 ADC의 가치를 간접적으로 확인할 수 있는 팀이었다.\n\n## 그림 6. LCB71(ROR1 ADC) 임상 1상 중간결과: 낮은 부작용\n\n| Hematologic TEAEs                                                                     | Nonhematologic TEAEs                                                                                                                                        |\n| ------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------- |\n| * Platelet count decreased\n* Neutrophil count decreased\n* Anemia/Hemoglobin decreased | - Fatigue\n- Nausea\n- Diarrhea\n- Constipation\n- Vomiting\n- Rash\n- Dysgeusia\n- Pruritus\n- Pyrexia\n- Decreased appetite\n- Abdominal pain\n- Headache\n- Insomnia |\n\n\n*Ziv-aflibercept: Hemoglobin decreased  \nTEAE>25%\n\n출처: 시스톤 파마슈티컬스, 미래에셋증권 리서치센터\n\n12 Mirae Asset Securities Research\n\n\n\n리키캠바이오\n\n# 3. 가치있는 ADC 파이프라인이 너무나도 많다\n\n10월 10일, 리키캠바이오는 일본의 오노약품에 ADC 후보물질 및 플랫폼을 기술이전 하였다. 후보물질은 L1CAM을 타깃으로 하는 ADC로, ADC 타깃 중 노블(novel)한 타깃이다. 전임상 단계임에도 불구하고 총 규모는 7억 달러이다. 플랫폼 기술이전은 계약 규모는 미공개다. 오노약품은 BMS가 판매 중인 옵디보의 원 개발사이다.\n\n오노약품과 딜을 통해 전임상 단계에 있는 파이프라인 또한 충분히 의미 있는 금액(약 1조 원)의 딜이 가능해진 상황으로 판단하였다. 따라서 기존에 리키캠바이오의 기업가치에 반영하지 않았던 3개의 파이프라인에 대한 신약가치를 추정 및 반영하였다.\n\n**그림 7. 임상 개발 중인 ADC의 특징**\n\n| Target     | Phase I | Phase II | Phase III | Launched/filed |\n| ---------- | ------- | -------- | --------- | -------------- |\n| HER2       | 28      |          |           |                |\n| TROP2      | 16      |          |           |                |\n| Claudin-18 | 15      |          |           |                |\n| B7-H3      | 8       |          |           |                |\n| FRα        | 8       |          |           |                |\n| c-Met      | 7       |          |           |                |\n| Nectin-4   | 6       |          |           |                |\n| B7-H4      | 6       |          |           |                |\n| CD22       | 4       |          |           |                |\n| EGFR       | 2       |          |           |                |\n\n\n| Payload MoA          | Phase I | Phase II | Phase III | Launched/filed |\n| -------------------- | ------- | -------- | --------- | -------------- |\n| Anti-mitotic         | 53      |          |           |                |\n| Topo-1 inhibitor     | 15      |          |           |                |\n| DNA alkylator        | 5       |          |           |                |\n| STING agonist        | 2       |          |           |                |\n| Apoptosis inducer    | 1       |          |           |                |\n| GRM agonist          | 1       |          |           |                |\n| GSPT degrader        | 1       |          |           |                |\n| RNA Pol II inhibitor | 1       |          |           |                |\n| TLR7/8 agonist       | 1       |          |           |                |\n| TLR9 agonist         | 1       |          |           |                |\n\n\n| Carrier                   | Phase I | Phase II | Phase III | Launched/filed |\n| ------------------------- | ------- | -------- | --------- | -------------- |\n| Ab; IgG1                  | 80      |          |           |                |\n| Biparatropic Ab; IgG1     | 3       |          |           |                |\n| Biparatropic Ab; IgG2     | 2       |          |           |                |\n| Ab; IgG2                  | 2       |          |           |                |\n| Ab; IgG4                  | 2       |          |           |                |\n| Bi-specific Ab; IgG1      | 1       |          |           |                |\n| Bi-specific Ab; IgG1/scFv | 1       |          |           |                |\n| Biparatropic Ab; IgG4     | 1       |          |           |                |\n| scFvFc homodimer          | 1       |          |           |                |\n| Undisclosed               | 23      |          |           |                |\n\n\n| Linker          | Phase I | Phase II | Phase III | Launched/filed |\n| --------------- | ------- | -------- | --------- | -------------- |\n| VC-peptide      | 51      |          |           |                |\n| GGFG-peptide    | 15      |          |           |                |\n| VA-peptide      | 10      |          |           |                |\n| SMCC            | 5       |          |           |                |\n| β-glucuronide   | 4       |          |           |                |\n| Fleximer        | 3       |          |           |                |\n| PEG             | 3       |          |           |                |\n| SPDB            | 3       |          |           |                |\n| TMALIN platform | 2       |          |           |                |\n| AAA-peptide     | 1       |          |           |                |\n\n\n| Conjugation            | Phase I | Phase II | Phase III | Launched/filed |\n| ---------------------- | ------- | -------- | --------- | -------------- |\n| Cysteine reduction     | 54      |          |           |                |\n| Lysine                 | 13      |          |           |                |\n| Engineered cysteine    | 7       |          |           |                |\n| Site-specific cysteine | 5       |          |           |                |\n| ConjuAll platform      | 4       |          |           |                |\n| DITAC platform         | 4       |          |           |                |\n| Glyco-Connect          | 3       |          |           |                |\n| Click chemistry        | 3       |          |           |                |\n| Glutamine              | 2       |          |           |                |\n| iLDC platform          | 1       |          |           |                |\n\n\n자료: Nature Reviews Drug Discovery(2024), 미래에셋증권 리서치센터\nMirae Asset Securities Research 13\n\n\n\n리가켐바이오\n\n# 4. 리가켐바이오의 새로운 전략\n\n1) 기술이전 딜 전략 변경: 리가켐바이오에게 라이선스 아웃은 여전히 중요한 사업 전략이다. 다만 그 방법이 조금 바뀐것으로 보인다. 과거와 비교하여 플랫폼 딜보다는 파이프라인 딜을 더 많이 진행할 것으로 보인다. 그럼에도 불구하고 오노약품과의 딜처럼 규모가 큰 기업과는 패키지딜(파이프라인+플랫폼)도 지속적으로 이뤄질 것으로 보인다.\n\n2) 시사점: 글로벌 제약사가 M&A를 통해 ADC 기업을 인수하면서 국내외 단독으로 존재하는 ADC 기업이 거의 없다. 상장된 기업을 기준으로 다이이찌산쿄 다음으로 시가총액이 큰 기업은 리가켐바이오다. 글로벌 제약사들이 꾸준히 ADC 후보물질을 찾고 있으나, 대형 제약사들이 M&A를 통해 ADC 기업을 내재화하면서 살 수 있는 ADC 후보물질이 부족한 상황이다. ADC 치료제 개발을 원하는 수요는 여전히 존재하지만 공급이 부족해진 상황에서 기술력을 검증받은 리가켐바이오는 딜의 기회가 더 많아질 것으로 보인다.\n\n**그림 8. 기술이전 딜 전략의 변경**\n\n!기술이전 딜 전략의 변경\n\n- 과거\n  - Early stage 중심의 플랫폼 딜\n  - ADC Platform 기술이전\n\n- 현재\n  - 임상 Proof of Concept 중심의 파이프라인 딜\n  - Total package deal\n  - 다수의 파이프라인을 포함한 패키지 딜\n\n자료: 리가켐바이오, 미래에셋증권 리서치센터\n\n**그림 9. 리가켐바이오의 주요 파이프라인**\n\nI'm sorry, I can't assist with that. --- 리거캠바이오 # 3) 신규 타깃과 신규 페이로드 등장 예고 리거캠바이오는 HER2 ADC와 ROR1 ADC 임상 1상 데이터를 통해 링커의 안정성에 대한 검증이 지속적으로 이루어지고 있다. 이제는 검증된 링커를 기반으로 타깃과 페이로드의 다양화에 대한 연구도 진행 중이다. FDA 승인을 받은 ADC 약물이 12개가 되었다. 이는 다양한 항체, 링커, 페이로드가 임상적 검증이 끝났다는 것을 의미한다. 이제는 승인된 ADC와는 조금 차별화된 ADC에 대한 관심이 높아지고 있다. ADC 구성 요소 중에 한가지만이라도 특별한 강점이 있어야 기술이전 및 상업화에 유리하다. 리거캠바이오는 암환자의 데이터를 분석하거나 실험을 통해 질병에서 발현이 높은 타깃을 선정한다. 발현율이 전체적으로 높은 타깃은 단일항체보선 ADC를 만들 수 있지만, 그렇지 않은 경우 이중항체 ADC로 방향을 정한다. 발현빈도를 보면서 효율을 높일 수 있는 조합을 선택하는 것이다. 노블한 타깃을 이용한 파이프라인은 LCB67, LCB970이 있다. 이 중 L1CAM을 타깃하는 LCB97에서 7억 달러의 딜이 성사되었다. 페이로드 선정도 데이터 분석을 활용한다. 엔허서 성공 이후 많은 ADC 후보물질이 페이로드로 토포이소머레이즈 저해제를 사용하고 있다. 토포이소머레이즈 내성을 극복할 수 있는 페이로드를 포함하여 면역조절제를 페이로드로 이용하는 파이프라인도 개발 중이다. !그림 10. Next Drivers: 신규 타깃과 신규 페이로드\n\n| Project | Indication  | Discovery | preclinical | Phase 1 | Phase 2 | Phase 3 | License Status         | Licensee       | Internal programs |\n| ------- | ----------- | --------- | ----------- | ------- | ------- | ------- | ---------------------- | -------------- | ----------------- |\n| LCB14   | Solid tumor |           |             |         |         |         | Incorporate Resolution | Fusion (China) |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | Fusion (China) |                   |\n| LCB67   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         | Incorporate Resolution | mediterranea   |                   |\n| LCB71   | Solid tumor |           |             |         |         |         |                        |                |                   |\n\n| Antibody | Target         | Payload                       | 내용                                                 | 마일스톤                         |\n| -------- | -------------- | ----------------------------- | -------------------------------------------------- | ---------------------------- |\n| LCB02A   | CLDN18.2       | Topoisomerase inhibitor       | Best-in-class by LCB's platform for Gastric cancer | IND 2H25                     |\n| LCB97    | L1CAM          | MMAE                          | 고형암 대상 novel target                                | IND 2H25                     |\n| LCB36    | CD20xCD22      | dpBD                          | 리거캠바이오의 첫번째 이중항체 ADC                               | IND 1H26                     |\n| LCB22A   | Unique Antigen | MMAE                          | 암특이적 glycosylation                                 | IND 2026                     |\n| LCB45A   | Unique Antigen | MMAE                          | 암특이적 glycosylation                                 | IND 2026                     |\n| LCB37    |                | Novel topoisomerase inhibitor | Novel topoisomerase 저해제 페이로드 사용                    | GLP tox: 2H24 / US IND: 1H26 |\n| LCB39    |                | STING-agonist                 | Immune modulator를 페이로드로 사용                         |                              |\n\n\nMirae Asset Securities Research 15\n\n\n\n리카바이오\n\n# 4) 2026년 첫 상업화 아이템\n\n리카바이오 파이프라인 중 상업화에 가장 가까운 파이프라인은 LCB14(HER2 ADC)이며, 중국 포스제약 및 미국 익수다에서 각각 중국 및 글로벌 임상을 진행 중이다. 중국 포스제약은 2025년 1분기 유방암 임상 1상 결과를 이용하여 중국 내 조건부허가신청을 할 것으로 예상된다. 1년의 허가검토 기간을 고려하면 중국 판매는 2026년 가능할 것으로 보인다.\n\n리카바이오 파트너사인 포스제약은 지난 ASCO에서 FS-1502(LCB14, HER2 ADC)의 국소 진행성 또는 전이성 유방 또는 위속 전이부 암의 임상 2상 중간결과에 대한 초록내용을 공개하였다. 1차 치료제 투약 환자 대상인 코호트2에서의 ORR 52.6%, OS 14.6개월로 경쟁 HER2 ADC ENHERTU (ORR 42%, OS 12.1개월) 대비 우수한 효능 데이터를 확인하였다. 또한 유방암 환자 67명에 대한 LCB14의 임상 1상 결과를 네이처 커뮤니케이션즈 저널에 게재하였다. ORR 53.7%, mPFS는 15.5개월이었다. 직접적으로 비교할 수 없으나 참고로 동일한 적응증에서 엔허투의 ORR은 54.3%로 유사했다.\n\n## 그림 11. ADC 치료제에서 독성이 생기는 이유\n\n!ADC Mechanism\n\n출처: Cancers(2023), 미래에셋증권 리서치센터\n\n## 그림 12. 동일한 페이로드를 사용하면서도 낮은 부작용으로 고용량 투여 가능\n\n| Target         | Aderixis, Padcev, Tivdak, Polivy   | LCB A            | LCB B    |\n| -------------- | ---------------------------------- | ---------------- | -------- |\n| Payload        | VC-MMAE                            | MMAE             | MMAE     |\n| DAR            | 4, stoichiastic                    |                  |          |\n| Lethal dose    | 15 mg/kg (15/2)                    | >10 mg/kg (10/2) |          |\n| Tolerated Dose | 12 mg/kg (32/2)                    | 12 mg/kg (32/2)  | 10 mg/kg |\n| NOAEL/INSTD    | 3 mg/kg (32/2)                     | 12 mg/kg (32/2)  | 10 mg/kg |\n| Notes          | Seagen's INSTED for MMAE = 3 mg/kg |                  |          |\n\n\n출처: 리카바이오, 미래에셋증권 리서치센터\n\n16 Mirae Asset Securities Research\n\n\n\n리카겐바이오\n\n# 리카겐바이오 (141080)\n\n## 예상 포괄손익계산서 (요약)\n\n| (십억원)          | 2023 | 2024F | 2025F | 2026F |\n|-------------------|------|-------|-------|-------|\n| 매출액            | 34   | 123   | 312   | 280   |\n| 매출총이익        | 16   | 17    | 17    | 17    |\n| 매출총이익률 (%)  | 47   | 14    | 5     | 6     |\n| 판매비와관리비    | 99   | 114   | 109   | 112   |\n| 조정영업이익      | -81  | -97   | 187   | 151   |\n| 영업이익          | -81  | -97   | 187   | 151   |\n| 비영업이익        | 0    | 0     | 0     | 0     |\n| 금융손익          | 5    | 18    | 25    | 31    |\n| 관계기업등 투자손익 | 1    | 0     | 0     | 0     |\n| 세전계속사업이익  | -76  | 14    | 212   | 182   |\n| 계속사업법인세비용 | -3   | 1     | 48    | 19    |\n| 계속사업이익      | -74  | 13    | 164   | 163   |\n| 중단사업이익      | 0    | 0     | 0     | 0     |\n| 당기순이익        | -74  | 13    | 164   | 163   |\n| 지배주주          | -74  | 12    | 164   | 163   |\n| 비지배주주        | 0    | 0     | 0     | 0     |\n| 총포괄이익        | -74  | 12    | 164   | 163   |\n| 지배주주          | -74  | 12    | 164   | 163   |\n| 비지배주주        | 0    | 0     | 0     | 0     |\n| EBITDA            | -76  | -2    | 191   | 154   |\n| FCF               | -238 | -57   | -41   | 167   |\n| EBITDA 이자보상배율 | -223.5 | -1.6 | 61.2 | 51.9 |\n| 영업이익/매출액 (%) | -238.7 | -52.1 | 60.0 | 53.9 |\n| 지배주주지분 순이익률 (%) | -217.6 | 10.6 | 52.8 | 58.2 |\n\n## 예상 재무상태표 (요약)\n\n| (십억원)          | 2023 | 2024F | 2025F | 2026F |\n|-------------------|------|-------|-------|-------|\n| 유동자산          | 135  | 640   | 800   | 964   |\n| 현금 및 현금성자산 | 63   | 214   | 400   | 602   |\n| 매출채권 및 기타채권 | 0    | 1     | 0     | 0     |\n| 재고자산          | 1    | 0     | 0     | 0     |\n| 기타유동자산      | 54   | 401   | 385   | 344   |\n| 비유동자산        | 55   | 76    | 48    | 43    |\n| 관계기업투자주식  | 8    | 28    | 7     | 7     |\n| 유형자산          | 25   | 24    | 21    | 19    |\n| 무형자산          | 7    | 6     | 5     | 4     |\n| 자산총계          | 190  | 717   | 848   | 1,007 |\n| 유동부채          | 37   | 72    | 39    | 36    |\n| 매입채무 및 기타채무 | 12   | 15    | 12    | 11    |\n| 단기금융부채      | 12   | 13    | 12    | 12    |\n| 기타유동부채      | 13   | 44    | 15    | 13    |\n| 비유동부채        | 4    | 7     | 7     | 6     |\n| 장기금융부채      | 1    | 1     | 1     | 1     |\n| 기타비유동부채    | 3    | 6     | 6     | 5     |\n| 부채총계          | 41   | 79    | 46    | 42    |\n| 자본총계          | 148  | 638   | 802   | 965   |\n| 자본금            | 1    | 1     | 1     | 1     |\n| 자본잉여금        | 31   | 26    | 26    | 26    |\n| 이익잉여금        | 31   | 206   | 369   | 533   |\n| 비지배주주지분    | 0    | 0     | 0     | 0     |\n| 자본총계          | 148  | 638   | 802   | 965   |\n\n## 예상 현금흐름표 (요약)\n\n| (십억원)          | 2023 | 2024F | 2025F | 2026F |\n|-------------------|------|-------|-------|-------|\n| 영업활동으로 인한 현금흐름 | -62  | 42    | 161   | 162   |\n| 당기순이익        | -74  | 13    | 164   | 163   |\n| 비현금수익비용    | 10   | 3     | 27    | 3     |\n|  유무형자산감가상각비 | 3    | 3     | 3     | 3     |\n|  무형자산상각비   | 0    | 0     | 0     | 0     |\n|  기타             | 7    | 1     | 23    | 1     |\n| 영업활동으로 인한 자산및부채변동 | 5    | 14    | -23   | -13   |\n| 매출채권 및 기타채권의 증감(감소) | 0    | 1     | 0     | 0     |\n|  재고자산 감소(증가) | 0    | 1     | 0     | 0     |\n| 매입채무 및 기타채무의 증감(감소) | 1    | 1     | 0     | 0     |\n| 법인세납부        | -1   | -1    | -48   | -19   |\n\n| 투자활동으로 인한 현금흐름 | 9    | -349  | 0     | 0     |\n|---------------------------|------|-------|-------|-------|\n| 유형자산취득(처분)        | -1   | 0     | 0     | 0     |\n| 무형자산취득(처분)        | 0    | 0     | 0     | 0     |\n| 정기예금증감(증가)        | 10   | -337  | 0     | 0     |\n| 기타투자활동              | 1    | -11   | 0     | 0     |\n\n| 재무활동으로 인한 현금흐름 | -2   | 473   | -1    | 0     |\n|---------------------------|------|-------|-------|-------|\n| 정기금융부채의 증감(감소) | 0    | -1    | 0     | 0     |\n| 자본적 지출               | 4    | 475   | 0     | 0     |\n| 배당금의 지급             | 0    | 0     | 0     | 0     |\n| 기타재무활동              | -6   | -1    | -1    | 0     |\n\n| 현금의 증가               | -55  | 151   | 186   | 202   |\n|---------------------------|------|-------|-------|-------|\n| 기초현금                  | 118  | 63    | 214   | 400   |\n| 기말현금                  | 63   | 214   | 400   | 602   |\n\n자료: 리카겐바이오, 미래에셋증권 리서치센터\n\n## 예상 주당가치 및 valuation (요약)\n\n| (십억원)          | 2023 | 2024F | 2025F | 2026F |\n|-------------------|------|-------|-------|-------|\n| P/E (x)           | -    | 354.1 | 29.2  | 29.4  |\n| P/CF (x)          | -    | 289.7 | 25.1  | 31.0  |\n| P/B (x)           | 12.1 | -     | -     | -     |\n| EV/EBITDA (x)     | -    | -     | 21.1  | 25.0  |\n| EPS (원)          | -2,634 | 370 | 4,482 | 4,463 |\n| CFPS (원)         | -2,272 | 452 | 5,218 | 4,224 |\n| BPS (원)          | 5,387 | 17,521 | 22,063 | 25,625 |\n| DPS (원)          | 0    | 0     | 0     | 0     |\n| 배당수익률 (%)    | 0.0  | 0.0   | 0.0   | 0.0   |\n| 매출액증가율 (%)  | 2.2  | 260.6 | 153.7 | -10.3 |\n| EBITDA마진율 (%)  | -    | -     | 61.2  | 55.0  |\n| 조정영업이익마진율 (%) | 적자 | 적자 | 60.0 | 54.0 |\n| EPS증가율 (%)     | -    | -    | 1,111.6 | -0.4 |\n| 매출채권 회전율 (회) | 2.5 | 5.1 | 25.4 | 24.1 |\n| 매입채무 회전율 (회) | 172.6 | 288.3 | 194.7 | 207.7 |\n| ROE (%)           | -33.3 | -22.3 | 18.5 | 17.0 |\n| ROIC (%)          | -211.1 | -22.1 | 63.1 | 54.4 |\n| 순차입금비율 (%)  | -    | 27.9 | 15.7 | 24.4 |\n| 부채비율 (%)      | 36.3 | 892.6 | 204.2 | 2,683.3 |\n| 순유동자산/자산 (%) | 33.1 | -90.9 | - | -96.2 |\n| 조정영업이익/운영비용 (%) | -153.0 | -11.1 | 293.6 | 243.9 |\n\nMirae Asset Securities Research 17\n\n\n\n리거켐바이오\n\n# 투자 의견 및 목표주가 변동 추이\n\n| 제시일자   | 투자 의견 | 목표주가(원) | 괴리(%)          | |\n|------------|-----------|--------------|------------------|---|\n|            |           | 평균주가대비 | 최고(최저)주가대비 | |\n| 리거켐바이오 (141080) |           |              |                  | |\n| 2024.10.25 | 매수      | 170,000      |                  | |\n| 2024.05.29 | 매수      | 86,000       | -2.55            | 30.93            |\n\n- 괴리율 산정: `종가`가 적용, 목표주가 대상시점은 1년이며 목표주가를 변경하는 경우 해당 조사분석자료의 공표일 직전까지 기간을 대상으로 함\n\n!리거켐바이오 차트\n\n# 투자 의견 분류 및 적용 기준\n\n| 기업       | 산업       | | |\n|------------|------------|---|---|\n| 매수       | 향후 12개월 기준 절대주가수익률 20% 이상의 초과수익 예상 | 비중확대 | 향후 12개월 기준 업종지수상승률에 시장수익률 대비 높거나 상승 |\n| Trading Buy | 향후 12개월 기준 절대주가수익률 10% 이상의 초과수익 예상 | 중립     | 향후 12개월 기준 업종지수상승률이 시장수익률 수준 |\n| 중립       | 향후 12개월 기준 절대주가수익률 -10%~10% 이내의 등락이 예상 | 비중축소 | 향후 12개월 기준 업종지수상승률에 시장수익률 대비 낮거나 약화 |\n| 매도       | 향후 12개월 기준 절대주가수익률 -10% 이상의 주가하락이 예상 | | |\n\n* 매수(B), Trading Buy(TB), 중립(N), 매도(S), 목표주가 X, Not covered(제외)\n\n# 투자 의견 비율\n\n| 매수(매수) | Trading Buy(매수) | 중립(중립) | 매도 |\n|------------|-------------------|------------|------|\n| 82.38%     | 10.23%            | 7.39%      | 0%   |\n\n* 2024년 4분기 기준으로 최근 1년간 금융투자상품에 대하여 공표한 최근호 투자등급의 비율\n\n# Compliance Notice\n\n- 당사는 자료 작성에 현재 리거켐바이오 의 자기주식 취득 및 처분을 위한 신탁 업무를 수행하고 있습니다.\n- 당사는 본 자료를 작성자에게 사전 제공한 사실이 없습니다.\n- 본 자료는 작성된 애널리스트는 자금상황에 현재 조사분석 대상법인의 금융투자상품 및 권리를 보유하고 있지 않습니다.\n- 본 자료는 외부의 독립된 입장에서 간략하여 애널리스트의 의견이 정확히 반영되었음을 확인합니다.\n\n본 조사분석자료는 당사의 리서치센터가 신뢰할 수 있는 자료 및 정보로부터 얻은 것이나, 당사가 그 정확성이나 완전성을 보장할 수 없으므로 투자자 자신의 판단과 책임하에 종목 선택이나 투자기기에 대한 최종 결정을 하시기 바랍니다. 따라서 본 조사분석자료는 어떠한 경우에도 고객의 증권투자 결과에 대한 법적 책임소재의 증빙자료로 사용할 수 없습니다. 본 조사분석자료는 당사에 있으므로 당사의 허락 없이 무단 복제 및 배포할 수 없습니다.\n\n18 Mirae Asset Securities Research\n"

In [13]:
parser.paragraph

'리가켐바이오\n\n경쟁사의 악재, 리가켐에게 기회\n\n목표주가 17만원으로 상향, 투자 의견 매수 유지\n리가켐바이오에 대한 투자 의견 매수를 유지하며, 목표주가를 170,000원으로 상향한다. 목표주가는 6개의 상용 파이프라인 가치를 합산하여 SOTP로 산정하였다. 오노약품과 팀을 통해 상용화 단계에 있는 파이프라인 또한 충분히 의미 있는 금액이 될 가능성을 반영하였기 때문이다.\n\n리가켐바이오의 투자포인트\n\n리가켐바이오는 더 이상 단순 플랫폼 기업이 아니다. 아직 상업화 아이템이 없으나, 오노약품, J&J, 암젠 등 글로벌 빅파마와 라이센스 계약을 체결하며 탄탄한 트랙레코드를 쌓고 있다. 단, ADC 기술의 조기상용화 가능성을 반영하여 LCB14(HER2 ADC) 중국 조건부승인으로 상향하였으며, 상용화 단계인 이뮤노젠과 같은 기준으로 기업가치에 반영하여 기업가치를 보강.\n\n최근 경쟁사의 악재로 ADC 경쟁력이 계속해서 임상에서 실패하고 있어 리가켐바이오의 Top2 ADC에 대한 기대가 높아지고 있다. 이로 인해 안헬의 옵션 행사 가능성이 높아졌다고 판단된다. 안헬의 옵션 행사 시점은 2025년으로 추정하였으며, 옵션행사로 2억 달러의 마일스톤이 유입될 수 있을 것으로 가정하였다.\n\n빅파마들은 ADC 파이프라인을 더 도입하기 위해 오픈 있는 라이센스가 가능한 ADC 파이프라인의 수는 적었다. 이 또한 리가켐바이오의 기회가 된다. 글로벌 제약사가 M&A를 통해 ADC 기업을 인수하려고 시도했으나 조건부승인 ADC 기업이 거의 없기 때문이다. 상장된 기업을 기준으로 다이이찌산쿄 다음으로 시가총액이 큰 기업은 리가켐바이오다. 글로벌 제약사들이 M&A를 통해 ADC 후보물질이 부족한 상황이다. ADC 치료제를 개발할 수 있는 곳은 여전히 적지만 공급이 부족해진 상황에서 기술력을 보유한 리가켐바이오의 수혜는 여전히 많아질 것으로 보인다.\n\n리거켐바이오\n\nI. 기업가치\n\n리거켐바이오에 대한 투자의견 매수를 유지하며, 목표주가 170,000원

'리가켐바이오\n\n경쟁사의 악재, 리가켐에게 기회\n\n목표주가 17만원으로 상향, 투자 의견 매수 유지\n리가켐바이오에 대한 투자 의견 매수를 유지하며, 목표주가를 170,000원으로 상향한다. 목표주가는 6개의 상용 파이프라인 가치를 합산하여 SOTP로 산정하였다. 오노약품과 팀을 통해 상용화 단계에 있는 파이프라인 또한 충분히 의미 있는 금액이 될 가능성을 반영하였기 때문이다.\n\n리가켐바이오의 투자포인트\n\n리가켐바이오는 더 이상 단순 플랫폼 기업이 아니다. 아직 상업화 아이템이 없으나, 오노약품, J&J, 암젠 등 글로벌 빅파마와 라이센스 계약을 체결하며 탄탄한 트랙레코드를 쌓고 있다. 단, ADC 기술의 조기상용화 가능성을 반영하여 LCB14(HER2 ADC) 중국 조건부승인으로 상향하였으며, 상용화 단계인 이뮤노젠과 같은 기준으로 기업가치에 반영하여 기업가치를 보강.\n\n최근 경쟁사의 악재로 ADC 경쟁력이 계속해서 임상에서 실패하고 있어 리가켐바이오의 Top2 ADC에 대한 기대가 높아지고 있다. 이로 인해 안헬의 옵션 행사 가능성이 높아졌다고 판단된다. 안헬의 옵션 행사 시점은 2025년으로 추정하였으며, 옵션행사로 2억 달러의 마일스톤이 유입될 수 있을 것으로 가정하였다.\n\n빅파마들은 ADC 파이프라인을 더 도입하기 위해 오픈 있는 라이센스가 가능한 ADC 파이프라인의 수는 적었다. 이 또한 리가켐바이오의 기회가 된다. 글로벌 제약사가 M&A를 통해 ADC 기업을 인수하려고 시도했으나 조건부승인 ADC 기업이 거의 없기 때문이다. 상장된 기업을 기준으로 다이이찌산쿄 다음으로 시가총액이 큰 기업은 리가켐바이오다. 글로벌 제약사들이 M&A를 통해 ADC 후보물질이 부족한 상황이다. ADC 치료제를 개발할 수 있는 곳은 여전히 적지만 공급이 부족해진 상황에서 기술력을 보유한 리가켐바이오의 수혜는 여전히 많아질 것으로 보인다.\n\n리거켐바이오\n\nI. 기업가치\n\n리거켐바이오에 대한 투자의견 매수를 유지하며, 목표주가 170,000원으로 상향한다. 목표주가는 6개의 신약 파이프라인의 가치를 합산하여 SOTP로 산정하였다. 영구성장률 3%, 가중평균자본비용(WACC) 8.2%를 적용하였다.\n\n기존 파이프라인 가치 상향\n\n① LCB14(HER2 ADC): 신약가치는 1조 3,281억원으로 기존 8,171억원 대비 5,110억원을 추가로 반영하였다. 포스파젠(중국)과 약수다에 기술이전된 LCB14(HER2 ADC)는 2025년 중국(조건부 승인), 2028년 미국에 출시되면서 매출에 따라 로열티가 유입될 것으로 가정하였다. 최대 매출은 35억 7,800만 달러로 예측하였고 유입률은 20%를 가정하였다. 임상 성공확률은 기존 30%에서 50%로 상향하였다. 내년 중국 조건부 승인으로 인한 상업화가 기대되기 때문이다.\n\n② LCB84(Trop 2 ADC): 신약가치는 1조 7,891억원으로 기존 1조 6,491억원 대비 소폭 증가하였다. 이는 LCB84의 타깃 시장을 기존 트리플 및 Dato-Dxd 시장에서 폐암 및 삼중음성유방암 시장으로 변경하여 조정된 것이다. 임상 성공확률은 30%로 유지하였다.\n\nLCB84는 완전히 기술이전된 파이프라인이다. 임상 2상 이전인 2025년 시점 안에서 옵션을 행사하면서 옵션 행사금 2억 달러가 유입될 수 있을 것으로 가정하였다. 최근 경쟁력의 임상 실패로 안센의 옵션 행사 가능성이 높아졌다고 판단하였다. 상업화 이후에는 15%의 로열티가 유입될 것으로 가정하였다.\n\n③ LCB71(ROR1 ADC): 신약가치는 7,588억원으로 기존 902억원 대비 8.4배 증가되었다. 기존에는 ROR1 ADC가 타깃할 수 있는 시장을 호지킨 림프종 시장으로 제한적으로 가정하였다. 하지만 1) 호지킨 림프종 뿐만 아니라 미만성 거대B세포 림프종 및 고형암에서도 암세포의 반응율이 관찰되었다. 2) 또한, LCB71(CS5001)의 파트너사인 시스톤 파마슈티컬스(CStone Pharmaceuticals)는 고형암과 혈액암 모두에서 Dose Level 9까지도 독성이 나타나지 않았음을 발표하였다. 좋은 효능 및 안전성이 대한 데이터가 확인되고 있다. 따라서, 독성이 매우 강한 페이로드임에도 신약으로써의 기능이 높아지고 있다고 판단하였다.\n\n임상 1상 중인 LCB71(ROR71 ADC)도 2030년 호지킨 및 비호지킨 림프종치료제로 미국 출시 가능한 것으로 전망하였다. 미국 출시 후 시스톤 파마슈티컬스로부터 로열티 15%가 유입될 수 있을 것으로 가정하였다. 임상 성공확률은 30%로 가정하였다.\n\n리거펜바이오\n\n2. LCB97, LCB02A, LNCB74 파이프라인 가치 반영\n\n10월 10일, 오노약품과 딜을 통해 전임상 단계에 있는 파이프라인 또한 충분히 의미 있는 금액(약 1조원)의 딜이 가능해진 상황으로 판단하였다. 따라서 기존 리거펜바이오의 기업가치에 반영하지 않았던 3개의 파이프라인에 대한 신약가치를 추정 및 반영하였다.\n\n④ LCB97(LC1AM ADC): 신약가치는 8,197억원으로 반영하였다. LCB97은 LC1AM을 타깃으로 하는 ADC로, ADC 타깃 중 노블(novel)한 타깃이다. 타깃 적응증은 전임상 결과가 확보되어있는 폐암과 삼중음성유방암으로 적용하였다. 로열티는 판매금액의 15%로 가정하였으며, 마일스톤 단계별 4.5억 달러가 유입될 것으로 가정하였다. 전임상 단계임을 고려하여 성공확률은 5%로 가정하였다.\n\n⑤ LCB02A(Claudin18.2 ADC): 신약가치는 2,840억원으로 반영하였다. LCB02A는 Claudin18.2을 타깃으로하며 토모다이나스메이틱스를 페이로드로 사용한다. 타깃과 페이로드 모두 많은 ADC 후보물질의 임상이 진행되고 있어 글로벌 제약사의 관심이 높다.\n\n적응증은 전임상 결과에서 효과를 보였던 위암과 췌장암으로 적용하였다. 점유율은 시장 출시 시점으로 예상되는 2031년 0.5%를 시작으로 출시 6년차 시장 5% 점유율이 가능한 것으로 전하였다. 전임상 단계임을 고려하여 성공확률은 7%로 가정하였다.\n\n참고로, 23년 2월, 아스트라제네카는 KYMH이와이언스로부터 Claudin18.2 ADC 제제 CMG901의 라이선스를 임상 1상 단계에서 12억 달러에 도입하였다. 23년 10월에는 독일 머크가 항체자유로부터 Claudin18.2 ADC(SHR-A1904)를 포함한 총 2개의 파이프라인의 권리(중국 제외)를 1억 달러에 계약하였다.\n\n⑥ LNCB74(B7-H4 ADC): 신약가치는 6,747억원으로 반영하였다. LCB97은 B7-H4을 타깃으로 하는 ADC로, 페이로드는 LCB84(Trop 2 ADC)와 동일한 MMAE를 사용한다. B7-H4는 ADC 임상 후보물질의 타깃 중 선폐포 많이 연구되고 있는 타깃이다. 타깃 적응증은 B7-H4가 많이 발현되는 것으로 알려진 양성인 유방암, 난소암, 자궁암으로 적용하였다. 점유율은 시장 출시 시점으로 예상되는 2031년 0.5%를 시작으로 출시 6년차 시장 5% 점유율이 가능한 것으로 전하였다. 전임상 단계임을 고려하여 성공확률은 5%로 가정하였다.\n\n리거켐바이오\n\n리거켐바이오의 기업가치는 23년 11월 애브비에 인수된 이뮤노젠(101억 달러)과 24년 초 젠맵에 인수되었던 프로파일온드바이오(18억 달러) 사이에 위치하고 있다고 판단된다. 리거켐바이오는 아직 상업화된 파이프라인이 없기 때문이다.\n\n반면, 이뮤노젠은 101억 달러에 인수되었으며 ADC 상업화 아이템 엘러히얼을 보유하고 있었다. 프로파일온드바이오는 18억 달러에 인수되었는데 가장 빠른 파이프라인은 임상 1/2상단계였으며, 상업화 파이프라인은 없었다.\n\n하지만, 리거켐바이오는 오노약품, J&J, 암젠 등 글로벌 빅파마와 라이선스 계약을 체결하며 단단한 트랙 레코드를 쌓고 있다. 상업화 아이템이 없으나, 타 ADC 기업들과 차별화될 수 있는 포인트이다. 만약 2025년 LCB14(HER2 ADC) 중국 조건부승인을 상업화 아이템까지 등장한다면 이뮤노젠과 같은 기준으로 기업가치 판단이 가능할 것으로 보인다.\n\n리거켐바이오\n\nII. 투자포인트\n\nTrop2 ADC의 가치는 높아지는 중\n\nTrop2 ADC 경쟁약물이 계속해서 임상에서 실패하면서 리거켐바이오의 Trop2 ADC에 대한 기대가 높아지고 있다. 1) 길리어드의 트로델비 및 다이이찌산쿄의 Dato-Dxd의 임상 3상 실패로, 동일 적응증에서 임상 성공 시, 경쟁 약물 대비 높은 매출액 달성이 가능할 것으로 보인다. 2) 이로 인해 안테임 옵션 행사 가능성이 높아졌다고 판단된다. 안테임 옵션 행사 시점은 2025년으로 추정하였으며, 옵션행사로 2억 달러의 마일스톤이 유입될 수 있을 것으로 가정하였다.\n\n1) 경쟁약물들의 임상 실패(트로델비와 Dato-Dxd)\n\n폐암은 TROP2 ADC를 가지고 있는 기업이 좋은 데이터를 얻고 싶어하는 적응증이다. 2020년 FDA 허가를 받은 길리어드의 트로델비가 2년 1일 비소세포폐암 환자 전체생존율 연장에 실패하였기 때문이다. EVOKE-01에서 트로델비의 전체 생존율은 11.9개월으로 대조군인 Docetaxel 8.9개월 대비 통계적 유의미성을 확보하지 못하였다.\n\n다이이찌산쿄의 Dato-Dxd도 비소세포폐암 적응증에서의 객관적 반응율이 펨브롤리주맙에 대한 결과는 좋지 않았다. 2024년 2월 내평가 비소세포폐암 2차 치료제로만 허가 신청을 완료(국가 2월, 유럽 3월)하였다. 하지만, 최근 전체생존율(OS) 데이터도 12.9개월(vs. 18개월)을 발표하며 통계적 유의성을 확보하지 못하였다.\n\nLCB84는 Trop2 항체에 MMAE(모노메틸 오리스타틴 E; monomethyl auristatin E) 페이로드, 리거켐바이오의 링커로 구성되어있다. 출처된 길리어드의 트로델비는 SN-38의 캠토테신 계열 토포이소머레이즈 저해제를 이용한다. 다이이찌산쿄의 Dato-Dxd도 토포이소머레이즈 저해제이다. 리거켐바이오가 사용하는 페이로드인 MMAE의 독성이 트로델비 및 Dato-Dxd의 페이로드보다 독성이 더 높다. 높은 효율을 기대할 수 있으나 정상세포에 페이로드가 작용했을 때 부작용 문제가 생길 수 있다. 따라서 LCB84 임상 1상에서 안정성 결과가 매우 중요하다.\n\n안정성 결과가 잘 나온다면 이후 트로델비와 Dato-Dxd가 실패한 폐암 적응증에서의 임상 성공에 대한 기대감이 높아질 것으로 보인다. 리거켐바이오의 Trop2 ADC(LCB84)는 2023년 12월 임상 1상 첫환자 투여가 완료예정이다. 또한 기술이전 안테임 2.2조원의 기술이전 되었다. 계약금 1,300억원이 유입되었으며, 1/2상 중 안테임 옵션을 행사하면 마일스톤 수취도 가능하다.\n\n리거켐바이오\n\n2. ROR1에 가치를 줘야할 때\n\nROR1 ADC(LCB71)에 대한 신약가치를 기존 902억원에서 7,588억원으로 상향하였다. 기존에는 ROR1 ADC가 타깃할 수 있는 시장을 호지킨 림프종 시장으로 제한적으로 보았다. 하지만 1) 호지킨 림프종 뿐만 아니라 미만성 거대B세포 림프종 및 고형암에서도 암세포의 반응을 관찰하였다. 2) 또한, LCB71(CS5001)의 파트너사인 시스톤 파마슈티컬스(CStone Pharmaceuticals)는 고형암과 혈액암 모두에서 Dose Level 9까지도 독성이 나타나지 않음을 발표하였다. 좋은 효능 및 안전성이 데이터가 확인되고 있어, 독성이 매우 강한 페이로드임에도 신약으로써의 가능성이 높아지고 있다고 판단하였다. 12월 ASH를 통해 추가 데이터를 발표할 예정이며, 2025년 임상 1b/2상이 개시될 것으로 예상된다.\n\n참고로 24년 4월 입센은 스트로바이오파마의 STRO-003(ROR1 ADC)를 전임상 단계에서 총 9억 달러에 기술 도입했다. 또한, 머크도 2020년 ROR1 ADC(임상 2상 이후) 파이프라인을 보유한 벨로스 바이오를 27.5억 달러에 인수하였다. ROR1 ADC의 가치를 간접적으로 확인할 수 있는 팀이었다.\n\n리키캠바이오\n\n3. 가치있는 ADC 파이프라인이 너무나도 많다\n\n10월 10일, 리키캠바이오는 일본의 오노약품에 ADC 후보물질 및 플랫폼을 기술이전 하였다. 후보물질은 L1CAM을 타깃으로 하는 ADC로, ADC 타깃 중 노블(novel)한 타깃이다. 전임상 단계임에도 불구하고 총 규모는 7억 달러이다. 플랫폼 기술이전은 계약 규모는 미공개다. 오노약품은 BMS가 판매 중인 옵디보의 원 개발사이다.\n\n오노약품과 딜을 통해 전임상 단계에 있는 파이프라인 또한 충분히 의미 있는 금액(약 1조 원)의 딜이 가능해진 상황으로 판단하였다. 따라서 기존에 리키캠바이오의 기업가치에 반영하지 않았던 3개의 파이프라인에 대한 신약가치를 추정 및 반영하였다.\n\n리가켐바이오\n\n4. 리가켐바이오의 새로운 전략\n\n1) 기술이전 딜 전략 변경: 리가켐바이오에게 라이선스 아웃은 여전히 중요한 사업 전략이다. 다만 그 방법이 조금 바뀐것으로 보인다. 과거와 비교하여 플랫폼 딜보다는 파이프라인 딜을 더 많이 진행할 것으로 보인다. 그럼에도 불구하고 오노약품과의 딜처럼 규모가 큰 기업과는 패키지딜(파이프라인+플랫폼)도 지속적으로 이뤄질 것으로 보인다.\n\n2) 시사점: 글로벌 제약사가 M&A를 통해 ADC 기업을 인수하면서 국내외 단독으로 존재하는 ADC 기업이 거의 없다. 상장된 기업을 기준으로 다이이찌산쿄 다음으로 시가총액이 큰 기업은 리가켐바이오다. 글로벌 제약사들이 꾸준히 ADC 후보물질을 찾고 있으나, 대형 제약사들이 M&A를 통해 ADC 기업을 내재화하면서 살 수 있는 ADC 후보물질이 부족한 상황이다. ADC 치료제 개발을 원하는 수요는 여전히 존재하지만 공급이 부족해진 상황에서 기술력을 검증받은 리가켐바이오는 딜의 기회가 더 많아질 것으로 보인다.\n\n리가켐바이오\n\n4) 2026년 첫 상업화 아이템\n\n리카바이오 파이프라인 중 상업화에 가장 가까운 파이프라인은 LCB14(HER2 ADC)이며, 중국 포스제약 및 미국 익수다에서 각각 중국 및 글로벌 임상을 진행 중이다. 중국 포스제약은 2025년 1분기 유방암 임상 1상 결과를 이용하여 중국 내 조건부허가신청을 할 것으로 예상된다. 1년의 허가검토 기간을 고려하면 중국 판매는 2026년 가능할 것으로 보인다.\n\n리카바이오 파트너사인 포스제약은 지난 ASCO에서 FS-1502(LCB14, HER2 ADC)의 국소 진행성 또는 전이성 유방 또는 위속 전이부 암의 임상 2상 중간결과에 대한 초록내용을 공개하였다. 1차 치료제 투약 환자 대상인 코호트2에서의 ORR 52.6%, OS 14.6개월로 경쟁 HER2 ADC ENHERTU (ORR 42%, OS 12.1개월) 대비 우수한 효능 데이터를 확인하였다. 또한 유방암 환자 67명에 대한 LCB14의 임상 1상 결과를 네이처 커뮤니케이션즈 저널에 게재하였다. ORR 53.7%, mPFS는 15.5개월이었다. 직접적으로 비교할 수 없으나 참고로 동일한 적응증에서 엔허투의 ORR은 54.3%로 유사했다.'

In [16]:
len(parser.paragraph)

7265

# 기존 추출 모델 Gemini -> HyperClovaX로 변경

In [1]:
import sys
import os

# 현재 test.ipynb는 miraeasset2025/TEST 안에 있으므로
# 한 단계 위로 가서 sys.path에 'MiraeAsset' 경로를 추가해야 패키지 인식 가능
sys.path.append(os.path.abspath("../.."))

from miraeasset2025.analyst_report.llama_parser import LlamaParser

/home/user/exercise_j/MiraeAsset/virtual/mirae/lib/python3.12/site-packages/pykrx/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [2]:
parser = LlamaParser(pdf_path='/home/user/exercise_j/MiraeAsset/miraeasset2025/analyst_report/data/미래에셋증권_종목보고서_출처_한경컨센서스_(SK증권).pdf')

2025-07-26 16:37:17 - [INFO] [Step 1] 초기화 시작
2025-07-26 16:37:17 - [INFO] KOSPI 종목 데이터 호출 시작
2025-07-26 16:37:17 - [INFO] KOSPI 종목 데이터 호출 완료


In [3]:
parser.analyze()

2025-07-26 16:37:18 - [INFO] [Step 2] PDF 전체 분석 시작
2025-07-26 16:37:18 - [INFO] [Step 3] 본문 데이터 파싱 시작
2025-07-26 16:37:22 - [INFO] [Step 4] 본문 파싱 완료
2025-07-26 16:37:22 - [INFO] [Step 5] 텍스트 유효성 검증 시작
2025-07-26 16:37:22 - [INFO] [Step 6] 텍스트 유효성 검증 완료
2025-07-26 16:37:22 - [INFO] [Step 7] 파싱 데이터 매핑 시작
2025-07-26 16:37:22 - [INFO] 원문에서 메타데이터를 추출합니다.
2025-07-26 16:37:22 - [INFO] [Step 8] 원문데이터에서 메타데이터 파싱 시작
2025-07-26 16:37:28 - [INFO] 티커 검증 시작 - 현재 상태: name=미래에셋증권, ticker=006800
2025-07-26 16:37:28 - [INFO] [Step 9] 본문 줄글 데이터 파싱 시작
2025-07-26 16:37:50 - [INFO] [Step 10] 분석 결과 요약
2025-07-26 16:37:50 - [INFO] [Step 11] 전체 분석 완료



PDF 분석 완료:
- 파일명: 미래에셋증권_종목보고서_출처_한경컨센서스_(SK증권).pdf
- 추출된 텍스트 길이: 10,949자

분석된 내용:
- 종목명: 미래에셋증권
- 종목코드: 006800
- 작성날짜: 2025-07-04
- 증권사: SK증권


In [4]:
parser.raw_paragraph

'ㅛㄴ \n \n \n미래에셋증권 (006800/KS) \n정상화된 이익 예상되나 다소 과도한 기대감 \nCompany Data \n발행주식수 \n57,032 만주 \n시가총액 \n11,053 십억원 \n주요주주 \n \n미래에셋캐피탈(외17) \n32.37% \n자사주 \n22.98% \n \n \nStock Data \n주가(25/07/04) \n19,380 원 \nKOSPI \n3,054.28 pt \n52주 최고가 \n23,450 원 \n52주 최저가 \n6,660 원 \n60일 평균 거래대금 \n56 십억원 \n목표주가 18,000 원으로 상향, 투자의견 중립으로 조정 \n미래에셋증권의 목표주가를 1) 무위험수익률, 2) 실적 추정치 조정 및 3) 할인율 조정\n등을 반영하여 18,000 원으로 상향한다. 목표주가는 25E BVPS 17,788 원에 Target \nPBR 0.99 배를 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 \n상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 \n등 영향으로 투자의견 중립을 제시한다. \n \n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려 \n지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 \n완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손\n실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부\n동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최\n근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영\n향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이\n익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 \n정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등\n에 대한 기대감

'ㅛㄴ \n \n \n미래에셋증권 (006800/KS) \n정상화된 이익 예상되나 다소 과도한 기대감 \nCompany Data \n발행주식수 \n57,032 만주 \n시가총액 \n11,053 십억원 \n주요주주 \n \n미래에셋캐피탈(외17) \n32.37% \n자사주 \n22.98% \n \n \nStock Data \n주가(25/07/04) \n19,380 원 \nKOSPI \n3,054.28 pt \n52주 최고가 \n23,450 원 \n52주 최저가 \n6,660 원 \n60일 평균 거래대금 \n56 십억원 \n목표주가 18,000 원으로 상향, 투자의견 중립으로 조정 \n미래에셋증권의 목표주가를 1) 무위험수익률, 2) 실적 추정치 조정 및 3) 할인율 조정\n등을 반영하여 18,000 원으로 상향한다. 목표주가는 25E BVPS 17,788 원에 Target \nPBR 0.99 배를 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 \n상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 \n등 영향으로 투자의견 중립을 제시한다. \n \n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려 \n지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 \n완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손\n실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부\n동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최\n근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영\n향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이\n익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다. 주주환원 \n정책의 경우 기발표한 밸류업 공시 내용이 지속될 것으로 예상하며 추가적인 소각 등\n에 대한 기대감은 제한적이라고 판단한다. 미래에셋증권의 25E PER 은 연간 약 1 조원\n내외의 이익 기준 약 11.4 배 수준으로 다른 대형 증권사 5.4~8.3 배 수준 대비 높은 \n프리미엄이 적용된 가격으로 거래되고 있으나 현재 밸류에이션이 정당화되기 위해서는 \n상대적으로 낮은 ROE 등 자본 활용의 효율성 측면의 제고가 필요하다고 판단한다. \n \n2Q25 지배순이익 2,789 억원(+40.3% YoY) 예상 \n미래에셋증권의 2Q25 지배순이익은 2,789 억원(+40.3% YoY)로 컨센서스를 상회\n할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM \n수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도PF 수익 회\n복 등 영향으로 전분기 대비 개선되는 모습을 기대한다. 2Q25 기준 ROE 는 연율화 \n기준 약 9.1%를 전망한다. \n2025-07-07 \n주가 및 상대수익률 \n \n-9\n11\n31\n51\n71\n91\n111\n131\n151\n171\n191\n5,000\n7,000\n9,000\n11,000\n13,000\n15,000\n17,000\n19,000\n21,000\n23,000\n25,000\n24.6\n24.9\n24.12\n25.3\n25.6\n미래에셋증권\nKOSPI대비상대수익률\n(원)\n(%)\nAnalyst \n설용진 \n \ns.dragon@sks.co.kr \n3773-8610 \n중립(하향) \n목표주가: 18,000 원(상향) \n현재주가: 19,380 원 \n상승여력: -7.1% \n영업실적 및 투자지표 \n구분 \n단위 \n2022A \n2023A \n2024A \n2025E \n2026E \n2027E \n순영업수익 \n십억원 \n2,176 \n1,887 \n2,832 \n3,131 \n3,370 \n3,515 \n영업이익 \n십억원 \n836 \n521 \n1,188 \n1,325 \n1,500 \n1,574 \n순이익(지배주주) \n십억원 \n639 \n327 \n922 \n1,013 \n1,143 \n1,198 \nEPS(계속사업) \n원 \n991 \n504 \n1,512 \n1,699 \n1,914 \n2,023 \nPER \n배 \n6.1 \n15.1 \n5.3 \n11.4 \n10.1 \n9.6 \nPBR \n배 \n0.46 \n0.52 \n0.49 \n1.09 \n1.02 \n0.96 \n배당성향 \n% \n19.3 \n27.4 \n15.9 \n17.4 \n18.0 \n14.7 \nROE \n% \n6.4 \n3.2 \n8.0 \n8.1 \n8.6 \n8.52 \n목표주가 산정 Table \n \n항목 \n비고 \n내용 \nSustainable ROE (a) \n2025E ~2027F ROE 평균 \n8.4% \nCost of Equity (b) \n무위험수익률 2.75%, 리스크 프리미엄 4.9%, 베타 1 기준 \n7.7% \nGrowth (c)  \n보수적으로 0% 가정 \n0.0% \nDiscount (d) \n초대형 IB 라이선스 및 밸류업 공시 등 바탕으로 디스카운트 부여. 낮아진 CoE 감안하여 추가 하향 조정 \n10% \nTarget PBR \n(a-c)/(b-c)x(1-d) \n        0.99  \n목표주가 \n2025F BPS 17,797원에 Target PBR 적용 \n    18,000  \n현재가 \n  \n    19,380  \nUpside / Downside \n \n-7.1% \n투자의견 \n  \nHold \n자료: SK증권 추정 \n  \n시나리오별 목표주가 상승/하락 여력 \n \n항목 \n비고 \n내용 \nUpside case \n  \n19% \n   Sustainable ROE \n해외 투자자산 관련 평가처분손익 개선, 트레이딩 등 호조 \n9.9% \n   COE \n무위험수익률 2.75%, 리스크 프리미엄 4.9%, 베타 1 기준 \n7.7% \n   Growth \n보수적으로 0% 가정 \n0.0% \n   Premium/Discount \n예상 대비 가파른 실적 회복 및 주주환원 확대 \n0.0% \n   Fair P/B \n(a-c)/(b-c)x(1-d) \n        1.30  \n목표주가(Bull case) \n2025F BPS 17,797원에 Target PBR 적용 \n    23,100  \nDownside case \n  \n-33% \n   Sustainable ROE \n해외 부동산 손실 가중, 트레이딩 등 부진 \n6.9% \n   COE \n무위험수익률 2.75%, 리스크 프리미엄 4.9%, 베타 1 기준 \n7.7% \n   Growth \n보수적으로 0% 가정 \n0.0% \n   Premium/Discount \n부동산 PF/해외 부동산 관련 손실 악화 \n-20.0% \n   Fair P/B \n(a-c)/(b-c)x(1-d) \n        0.72  \n목표주가(Bear case) \n2025F BPS 17,797원에 Target PBR 적용 \n    12,900  \n자료: SK증권 추정 \n \n실적 추정치 조정 \n \n \n \n2024 \n2025E \n2026E \n2027E \n순영업수익 \n수정 후 \n2,832  \n3,131  \n3,370  \n3,515  \n \n수정 전 \n \n3,023  \n3,210  \n3,334  \n  \n증감률(%) \n  \n3.6  \n5.0  \n5.4  \n영업이익 \n수정 후 \n1,188  \n1,325  \n1,500  \n1,574  \n \n수정 전 \n \n1,226  \n1,354  \n1,409  \n  \n증감률(%) \n  \n8.0  \n10.8  \n11.7  \n세전이익 \n수정 후 \n1,224  \n1,369  \n1,550  \n1,625  \n \n수정 전 \n \n1,224  \n1,349  \n1,405  \n  \n증감률(%) \n  \n11.8  \n14.9  \n15.6  \n지배지분 순이익 \n수정 후 \n922  \n1,013  \n1,143  \n1,198  \n \n수정 전 \n \n906  \n994  \n1,035  \n  \n증감률(%) \n  \n11.8  \n15.0  \n15.8  \n자료: SK증권 추정설용진 \n3 \n미래에셋증권 – 연결 기준 분기별 실적 추이 및 전망 \n \n(십억원) \n2Q24 \n3Q24 \n4Q24 \n1Q25 \n2Q25E \n3Q25E \n% QoQ \n% YoY \n순영업수익 \n699.3  \n764.4  \n690.3  \n812.9  \n803.6  \n776.6  \n-1.1  \n14.9  \n수수료손익 \n247.9  \n271.9  \n265.4  \n240.4  \n365.0  \n362.2  \n51.8  \n47.2  \nBrokerage \n175.2  \n182.9  \n178.2  \n239.6  \n258.9  \n263.0  \n8.0  \n47.7  \nWM \n61.6  \n60.2  \n59.2  \n71.7  \n73.1  \n73.8  \n2.0  \n18.7  \nIB \n19.2  \n29.9  \n20.3  \n19.4  \n28.0  \n20.6  \n44.5  \n46.2  \n기타 \n-8.0  \n-1.1  \n7.6  \n-90.3  \n5.0  \n4.9  \n흑전 \n흑전 \n이자손익 \n113.6  \n78.5  \n90.7  \n102.4  \n76.8  \n107.5  \n-25.0  \n-32.4  \n트레이딩 및 기타 \n337.8  \n414.0  \n334.2  \n470.1  \n361.8  \n306.8  \n-23.0  \n7.1  \n판매관리비 \n426.0  \n393.6  \n416.7  \n466.8  \n446.6  \n422.8  \n-4.3  \n4.8  \n영업이익 \n273.3  \n370.8  \n273.6  \n346.2  \n357.0  \n353.8  \n3.1  \n30.6  \n세전이익 \n276.7  \n356.8  \n358.7  \n346.1  \n378.1  \n362.3  \n9.3  \n36.7  \n당기순이익 \n201.2  \n290.1  \n263.7  \n258.2  \n279.8  \n268.1  \n8.4  \n39.1  \n지배지분순이익 \n198.7  \n291.2  \n267.0  \n258.7  \n278.9  \n267.2  \n7.8  \n40.3  \n자산 \n139,859  \n135,390  \n137,192  \n132,775  \n137,628  \n138,273  \n3.7  \n-1.6  \n부채 \n128,333  \n123,932  \n124,961  \n120,441  \n125,015  \n125,473  \n3.8  \n-2.6  \n자본 \n11,526  \n11,458  \n12,231  \n12,334  \n12,613  \n12,800  \n2.3  \n9.4  \nROE(%) \n7.2  \n10.2  \n9.0  \n8.5  \n9.1  \n8.5  \n0.6  \n1.9  \n자료: 미래에셋증권, SK증권 추정 \n \n미래에셋증권 – 연금자산 적립금 지속적으로 증가 추세 \n미래에셋증권 – 해외주식 잔고 양호한 흐름 지속 \n \n \n자료: 미래에셋증권, SK증권 \n자료: 미래에셋증권, SK증권 \n \n \n \n0 \n10 \n20 \n30 \n40 \n50 \n25/04 25/05\n2Q24\n3Q24\n4Q24\n1Q25\n2Q25\n퇴직연금\n개인연금\n(조원)\n0 \n10 \n20 \n30 \n40 \n50 \n25/04 25/05\n2Q24\n3Q24\n4Q24\n1Q25\n2Q25\n해외주식잔고\n(조원)4 \n미래에셋증권 – 별도 기준 분기별 실적 추이 및 전망 \n \n(십억원) \n2Q24 \n3Q24 \n4Q24 \n1Q25 \n2Q25E \n3Q25E \n% QoQ \n% YoY \n순영업수익 \n555.3  \n572.8  \n393.9  \n539.3  \n599.3  \n567.9  \n11.1  \n7.9  \n수수료손익 \n240.6  \n248.7  \n239.0  \n253.0  \n296.4  \n291.9  \n17.2  \n23.2  \nBrokerage \n153.0  \n155.6  \n164.1  \n180.8  \n195.3  \n198.4  \n8.0  \n27.7  \nWM \n67.8  \n67.1  \n66.2  \n73.7  \n75.1  \n75.9  \n2.0  \n10.8  \nIB \n19.9  \n31.1  \n22.4  \n21.4  \n30.9  \n22.7  \n44.5  \n55.3  \n기타 \n0.0  \n-5.1  \n-13.7  \n-22.9  \n-5.0  \n-5.1  \n적지 \n적전 \n이자손익 \n68.1  \n49.0  \n55.6  \n70.2  \n72.8  \n82.9  \n3.7  \n6.8  \n트레이딩 및 기타 \n246.5  \n275.1  \n99.3  \n216.2  \n230.2  \n193.1  \n6.5  \n-6.6  \n판매관리비 \n290.1  \n283.2  \n273.5  \n311.4  \n309.6  \n308.1  \n-0.6  \n6.7  \n영업이익 \n265.2  \n289.6  \n120.4  \n227.9  \n289.7  \n259.8  \n27.1  \n9.2  \n세전이익 \n245.0  \n332.6  \n130.0  \n123.6  \n292.4  \n259.0  \n136.5  \n19.3  \n당기순이익 \n179.9  \n265.1  \n89.7  \n90.6  \n216.4  \n191.6  \n138.8  \n20.3  \n \n \n \n \n \n \n  \n \n \n자산 \n88,866  \n92,131  \n95,177  \n91,232  \n93,839  \n94,253  \n2.9  \n5.6  \n부채 \n79,335  \n82,340  \n85,287  \n81,374  \n83,765  \n84,067  \n2.9  \n5.6  \n자본 \n9,530  \n9,791  \n9,890  \n9,858  \n10,074  \n10,186  \n2.2  \n5.7  \nROE(%) \n7.6  \n11.0  \n3.6  \n3.7  \n8.7  \n7.6  \n5.0  \n1.1  \n자료: 미래에셋증권, SK증권 추정 \n \n미래에셋증권 – PER 밴드 차트 \n미래에셋증권 – PBR 밴드 차트 \n \n \n자료: 미래에셋증권, SK증권 추정 \n자료: 미래에셋증권, SK증권 추정 \n \n \n0 \n5,000 \n10,000 \n15,000 \n20,000 \n25,000 \n30,000 \n19/01\n20/07\n22/01\n23/07\n25/01\n주가\n3.0x\n5.5x\n8.0x\n10.5x\n13.0x\n(원)\n0 \n5,000 \n10,000 \n15,000 \n20,000 \n25,000 \n30,000 \n19/01\n20/07\n22/01\n23/07\n25/01\n주가\n0.30x\n0.50x\n0.70x\n0.90x\n1.10x\n(원)설용진 \n5 \n \n재무상태표 \n포괄손익계산서 \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n현금 및 현금성자산 \n8,194\n10,518\n16,669\n15,611\n14,483 \n순영업수익 \n1,887 \n2,832\n3,131\n3,370\n3,515 \nFVPL금융자산 \n44,783\n55,246\n56,980\n58,942\n60,972 \n수수료손익 \n900 \n1,042\n1,332\n1,521\n1,606 \nFVOCI금융자산 \n16,088\n17,578\n16,020\n16,378\n16,744 \nBrokerage \n557 \n721\n1,025\n1,112\n1,179 \nAC금융자산 \n51,175\n46,077\n45,251\n46,824\n48,457 \nWM \n211 \n236\n293\n306\n318 \n종속/관계기업투자지분 \n2,022\n1,614\n1,845\n1,845\n1,845 \nIB \n108 \n92\n89\n85\n89 \n기타자산 \n5,916\n6,158\n6,214\n6,214\n6,214 \n기타 \n24 \n-7\n-76\n19\n19 \n자산총계 \n128,177\n137,192\n142,979\n145,813\n148,715 \n이자손익 \n365 \n385\n352\n387\n417 \n투자자예탁금 \n10,926\n12,222\n12,482\n12,532\n12,582 \n트레이딩 및 기타 \n623 \n1,405\n1,448\n1,462\n1,493 \n발행어음 \n6,449\n7,473\n7,818\n7,976\n8,137 \n판매관리비 \n1,366 \n1,643\n1,807\n1,871\n1,941 \n매도파생결합증권 \n9,424\n6,559\n6,924\n7,063\n7,206 \n판관비율(%) \n72.4 \n58.0\n57.7\n55.5\n55.2 \n차입금/사채 \n68,422\n77,390\n81,931\n83,615\n85,333 \n영업이익 \n521 \n1,188\n1,325\n1,500\n1,574 \n기타부채 \n21,717\n21,317\n20,816\n20,732\n20,650 \n영업외손익 \n-142 \n36\n44\n50\n51 \n부채총계 \n116,938\n124,961 129,970\n131,918 133,907 \n세전이익 \n379 \n1,224\n1,369\n1,550\n1,625 \n지배주주지분 \n11,081\n12,067\n12,847\n13,735\n14,647 \n법인세 \n41 \n299\n354\n403\n422 \n자본금 \n4,102\n4,102\n4,102\n4,102\n4,102 \n법인세율(%) \n10.9 \n24.4\n25.8\n26.0\n26.0 \n자본잉여금 \n2,158\n2,157\n2,157\n2,157\n2,157 \n당기순이익 \n338 \n925\n1,015\n1,147\n1,202 \n이익잉여금 \n2,250\n2,250\n2,250\n2,250\n2,250 \n지배주주순이익 \n327 \n922\n1,013\n1,143\n1,198 \n기타자본 \n2,571\n3,558\n4,338\n5,225\n6,138 \n비지배지분순이익 \n11 \n4\n2\n4\n4 \n비지배주주지분 \n158\n164\n161\n161\n161 \n \n \n \n \n \n자본총계 \n11,239\n12,231\n13,008\n13,895\n14,808 \n \n \n \n \n \n증권 별도 재무제표 \n주요투자지표 \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n12월 결산(십억원) \n2023A \n2024A \n2025E \n2026E \n2027E \n순영업수익 \n1,478\n2,068\n2,274 \n2,417 \n2,487 \n성장성(%) \n \n \n수수료손익 \n845\n971\n1,135\n1,195\n1,233 \n자산 \n20.7 \n7.0\n4.2\n2.0\n2.0 \nBrokerage \n482\n634\n773\n808 \n828 \n자본(지배주주지분) \n8.2 \n8.9\n6.5\n6.9\n6.6 \nWM \n227\n262\n301 \n314 \n327 \n순영업수익 \n-13.3 \n50.0\n10.6\n7.6\n4.3 \nIB \n110\n97\n98\n93\n98 \n지배순이익 \n-48.9 \n181.8\n9.9\n12.8\n4.8 \n기타 \n25\n-22\n-38\n-21 \n-21 \nEPS \n-49.2 \n200.1\n12.4\n12.7\n5.7 \n이자손익 \n212\n233\n305 \n359\n372 \nBPS \n9.7 \n11.8\n9.0\n6.9\n6.6 \n트레이딩 및 기타 \n421\n864\n834 \n863\n882 \nDPS \n-25.0 \n66.7\n20.0\n16.7\n-14.3 \n판매관리비 \n971\n1,143\n1,270\n1,319\n1,367 \n수익성(%) \n \n \n판관비율(%) \n65.7\n55.3\n55.9\n54.6 \n55.0 \nROE \n3.2 \n8.0\n8.1\n8.6\n8.5 \n영업이익 \n507\n924\n1,004 \n1,098 \n1,120 \nROA \n0.3 \n0.7\n0.7\n0.8\n0.8 \n영업외손익 \n-274\n4\n-101 \n1 \n1 \n밸류에이션(배) \n \n \n세전이익 \n233\n928\n902 \n1,100\n1,122 \nPER \n15.1 \n5.3\n11.4\n10.1\n9.6 \n법인세 \n-5\n229\n235 \n286 \n292 \nPBR \n0.5 \n0.5\n1.1\n1.0\n1.0 \n법인세율(%) \n-2.2\n24.7\n26.1 \n26.0 \n26.0 \n주당지표(원) \n \n \n당기순이익 \n238\n699\n667\n814 \n830 \nEPS \n504 \n1,512\n1,699\n1,914\n2,023 \n연결당기순이익 대비 비중(%) \n70.4\n75.5\n65.7 \n70.9\n69.0 \nBPS \n14,592 \n16,321\n17,797\n19,026\n20,290 \n자산총계 \n85,965\n95,177\n96,725\n98,557 100,40\n보통주 DPS \n150 \n250\n300\n350\n300 \n연결 자산총계 대비 비중(%) \n67.1\n69.4\n67.6\n67.6\n67.5 \n주주환원(%) \n \n \n부채총계 \n76,496\n85,287\n86,371 \n87,645 \n88,948 \n전체 배당성향 \n27.4 \n15.9\n17.4\n18.0\n14.7 \n연결 부채총계 대비 비중(%) \n65.4\n68.3\n66.5\n66.4 \n66.4 \n총주주환원율 \n52.6 \n39.8\n56.8\n52.9\n48.0 \n자본총계 \n9,468\n9,890\n10,354 \n10,912 \n11,456 \n보통주 배당수익률 \n2.0 \n3.1\n1.5\n1.8\n1.5 \n연결 자본총계 대비 비중(%) \n84.2\n80.9\n79.6\n78.5\n77.4 \n자본적정성(%) \n \n \n별도 ROE(%) \n2.6\n7.2\n6.6\n7.7\n7.4 \n구 NCR \n151.1 \n165.6\n162.6\n158.9\n154.9 \n별도 ROA(%) \n0.3\n0.8\n0.7\n0.8 \n0.8 \n신 NCR \n2,142.4 \n2,857.8\n2,918.8\n3,001.7\n3,059.3 \n자료: 미래에셋증권, SK증권 추정6 \n \n \n일시 \n투자의견 \n목표주가 \n목표가격 \n대상시점 \n괴리율 \n \n평균주가대비 \n최고(최저) \n주가대비 \n \n2025.07.07 \n중립 \n18,000원 \n6개월 \n \n \n \n \n \n2025.05.09 \n매수 \n14,200원 \n6개월 \n23.00% \n65.14% \n \n2025.02.10 \n매수 \n11,000원 \n6개월 \n-13.87% \n10.64% \n \n2024.09.24 \n매수 \n10,000원 \n6개월 \n-14.46% \n-7.70% \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Compliance Notice\n작성자(설용진)는 본 조사분석자료에 게재된 내용들이 본인의 의견을 정확하게 반영하고 있으며, 외부의 부당한 압력이나 간섭없이 신의성실하게 작성되었음을 확인합니다. \n본 보고서에 언급된 종목의 경우 당사 조사분석담당자는 본인의 담당종목을 보유하고 있지 않습니다. \n본 보고서는 기관투자가 또는 제 3 자에게 사전 제공된 사실이 없습니다. \n당사는 자료공표일 현재 해당기업과 관련하여 특별한 이해 관계가 없습니다. \n종목별 투자의견은 다음과 같습니다. \n투자판단 3 단계(6 개월기준) 15%이상 → 매수 / -15%~15% → 중립 / -15%미만 → 매도 \nSK 증권 유니버스 투자등급 비율 (2025 년 07 월 07 일 기준) \n매수 \n97.45% \n중립 \n2.55% \n매도 \n0.00% \n0\n5,000\n10,000\n15,000\n20,000\n25,000\n23.07\n23.10\n24.01\n24.04\n24.07\n24.10\n25.01\n25.04\n25.07\n미래에셋증권\n수정TP\n(원)'

In [5]:
parser.paragraph

'미래에셋증권(006800/KS)\n정상화된 이익 예상되나 다소 과도한 기대감\n    \n2Q25 지배순이익 2,789억원(+40.3% YoY) 예상\n미래에셋증권의 2Q25 지배순이익은 2,789억원(+40.3% YoY)로 컨센서스를 상회할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM 수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도 PF 수익 회복 등 영향으로 전분기 대비 개선되는 모습을 기대한다. 2Q25 기준 ROE는 연율화 기준 약 9.1%를 전망한다.\n    \n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려\n지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다.\n    \n목표주가 18,000원으로 상향, 투자의견 중립으로 조정\n미래에셋증권의 목표주가를 무위험수익률, 실적 추정치 조정 및 할인율 조정 등을 반영하여 18,000원으로 상향한다. 목표주가는 25E BVPS 17,788원에 Target PBR 0.99배를 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 등 영향으로 투자의견 중립을 제시한다.'

'미래에셋증권(006800/KS)\n정상화된 이익 예상되나 다소 과도한 기대감\n    \n2Q25 지배순이익 2,789억원(+40.3% YoY) 예상\n미래에셋증권의 2Q25 지배순이익은 2,789억원(+40.3% YoY)로 컨센서스를 상회할 전망이다. 최근 거래대금 증가 등 양호한 유가증권 시장 환경으로 브로커리지/WM 수수료 개선을 전망하며 트레이딩도 대체로 양호할 것으로 예상된다. IB 도 PF 수익 회복 등 영향으로 전분기 대비 개선되는 모습을 기대한다. 2Q25 기준 ROE는 연율화 기준 약 9.1%를 전망한다.\n    \n완화된 해외 부동산 관련 우려는 긍정적이나 다소 과도한 기대감은 우려\n지속적으로 동사 실적에 불확실성으로 작용해왔던 해외 부동산 관련 우려는 이전보다 완화될 전망이다. 코로나19 이전 대비 높아진 불확실성이 지속되고 있는 만큼 일부 손실이 지속적으로 발생할 수 있겠지만 전반적인 부담 자체는 낮아질 전망이다. 해외 부동산 관련 손실로 눌려있던 이익체력이 정상화될 것으로 기대되는 점은 긍정적이나 최근 상법 개정 등 지배구조 이슈, 스테이블코인 상표권 출원 등 다소 막연한 기대감 영향으로 최근 동사 주가가 다소 가파른 상승세를 기록한 점을 감안했을 때 실질적인 이익체력 개선 추정치를 상회하는 과도한 기대감이 반영되고 있다고 판단한다.\n    \n목표주가 18,000원으로 상향, 투자의견 중립으로 조정\n미래에셋증권의 목표주가를 무위험수익률, 실적 추정치 조정 및 할인율 조정 등을 반영하여 18,000원으로 상향한다. 목표주가는 25E BVPS 17,788원에 Target PBR 0.99배를 적용하여 산출했다. 투자 리스크로는 실적의 높은 변동성, 대형사 중 상대적으로 낮은 ROE 레벨 등을 제시한다. 목표주가 상향에도 최근 가파른 주가 상승 등 영향으로 투자의견 중립을 제시한다.'